#!/usr/bin/env python3
"""Generate the Skills Canada video copy refresh migration.

Reads scripts/data/copy-updates/skills-canada-video-copy-update.json, validates
the same shape constraints as the preflight (count, dedupe, non-empty
takeaway, expected category histogram), and emits a single UPDATE migration
with a row-count assertion. Does not contact Supabase; run the preflight first
if you want live-DB verification.

Targets rows by stable `skills-canada-NNN` id, not slug — see the preflight
script for the rationale.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


DATA_PATH = Path("scripts/data/copy-updates/skills-canada-video-copy-update.json")
MIGRATIONS_DIR = Path("supabase/migrations")
EXPECTED_ROW_COUNT = 8
EXPECTED_HISTOGRAM = {"life-skills": 8}
REQUIRED_FIELDS = ("id", "slug", "category", "title",
                   "old_description", "new_takeaway")
ID_PREFIX = "skills-canada-"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", type=Path, default=DATA_PATH)
    parser.add_argument("--output", type=Path, default=None,
                        help="Output SQL path (default: timestamped file under supabase/migrations)")
    args = parser.parse_args()

    rows = json.loads(args.data.read_text())
    errors = validate(rows)
    if errors:
        print("Refusing to write SQL:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    output = args.output or default_output_path()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_sql(rows, args.data))
    print(f"Wrote {output}")
    return 0


def validate(rows: list[dict[str, Any]]) -> list[str]:
    errors: list[str] = []

    if len(rows) != EXPECTED_ROW_COUNT:
        errors.append(f"row count is {len(rows)}, expected {EXPECTED_ROW_COUNT}")

    ids = [r.get("id") for r in rows]
    if len(set(ids)) != len(ids):
        dupes = sorted({i for i in ids if ids.count(i) > 1})
        errors.append(f"duplicate ids: {dupes}")

    for index, row in enumerate(rows, start=1):
        missing = [field for field in REQUIRED_FIELDS if field not in row]
        if missing:
            errors.append(f"row {index} ({row.get('id')}) missing fields: {missing}")
            continue
        value = row["new_takeaway"]
        if not isinstance(value, str) or not value.strip():
            errors.append(f"row {index} ({row['id']}) empty new_takeaway")
        if not isinstance(row["id"], str) or not row["id"].startswith(ID_PREFIX):
            errors.append(f"row {index} ({row['id']}) id must start with {ID_PREFIX!r}")
        if row["category"] not in EXPECTED_HISTOGRAM:
            errors.append(f"row {index} ({row['id']}) unexpected category {row['category']!r}")

    histogram = dict(Counter(r.get("category") for r in rows))
    if histogram != EXPECTED_HISTOGRAM:
        errors.append(f"category histogram is {histogram}, expected {EXPECTED_HISTOGRAM}")

    return errors


def default_output_path() -> Path:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    return MIGRATIONS_DIR / f"{stamp}_refresh_skills_canada_video_copy_pilot.sql"


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_value_row(row: dict[str, Any]) -> str:
    return f"      ({quote(row['id'])}, {quote(row['new_takeaway'])})"


def render_sql(rows: list[dict[str, Any]], source: Path) -> str:
    values_block = ",\n".join(render_value_row(row) for row in rows)
    return f"""-- Refresh takeaway for the {EXPECTED_ROW_COUNT} life-skills Skills Canada videos (pilot batch).
-- Generated by scripts/generate-skills-canada-copy-migration.py from {source}.
-- Targets rows by stable id; descriptions are intentionally left untouched.
-- Fails the transaction if the expected number of rows is not updated.

do $$
declare
  expected_count int := {EXPECTED_ROW_COUNT};
  actual_count int;
begin
  with v(id, new_takeaway) as (values
{values_block}
  )
  update public.content c
  set takeaway = v.new_takeaway
  from v
  where c.id = v.id
    and c.content_type = 'video'
    and c.id like 'skills-canada-%';

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
"""


if __name__ == "__main__":
    sys.exit(main())
