#!/usr/bin/env python3
"""Generate the skills-canada -> skilled-trades rename migration and its rollback.

Reads the client-approved decision artifact and renders:
  supabase/migrations/20260805210000_rename_skills_canada_to_skilled_trades.sql
  scripts/data/rollbacks/rename_skills_canada_to_skilled_trades_rollback.sql

Both files are deterministic functions of the artifact; rerun this script after
any artifact change and commit the regenerated SQL.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ARTIFACT = os.path.join(ROOT, "scripts/data/category-migrations/skills-canada-to-skilled-trades.json")
MIGRATION = os.path.join(ROOT, "supabase/migrations/20260805210000_rename_skills_canada_to_skilled_trades.sql")
ROLLBACK = os.path.join(ROOT, "scripts/data/rollbacks/rename_skills_canada_to_skilled_trades_rollback.sql")

EX_JOB_BOARD = {
    "skills-canada-123", "skills-canada-135", "skills-canada-139",
    "skills-canada-141", "skills-canada-145", "skills-canada-147",
    "skills-canada-152",
}
VALID_TARGETS = {
    "emerging-careers", "on-the-job", "life-skills", "mindsets",
    "how-i-got-here", "problems-to-solve", "post-secondary",
}


def validate(artifact):
    videos = artifact["videos"]
    ids = [v["content_id"] for v in videos]
    assert len(ids) == 160 and len(set(ids)) == 160, "expected 160 unique content ids"
    expected_ids = {f"skills-canada-{i:03d}" for i in range(1, 161)}
    assert set(ids) == expected_ids, "content id set is not skills-canada-001..160"

    keepers = [v for v in videos if v["action"] == "keep-skilled-trades"]
    leavers = [v for v in videos if v["action"] == "remove-skilled-trades"]
    assert len(keepers) == 101, f"expected 101 keepers, got {len(keepers)}"
    assert len(leavers) == 59, f"expected 59 leavers, got {len(leavers)}"
    assert len(keepers) + len(leavers) == 160

    jb = {v["content_id"] for v in videos if v["approved_recommendation"] == "Job Board"}
    assert jb == EX_JOB_BOARD, f"ex-job-board exception list mismatch: {sorted(jb)}"

    for v in keepers:
        assert v["effective_topical_target"] is None
    for v in leavers:
        assert v["effective_topical_target"] in VALID_TARGETS, v

    r = artifact["rename"]
    assert r["from"]["slug"] == "skills-canada" and r["to"]["slug"] == "skilled-trades"
    return sorted(k["content_id"] for k in keepers), sorted(
        (v["content_id"], v["effective_topical_target"]) for v in leavers
    )


def sql_id_values(ids, indent="    "):
    return ",\n".join(f"{indent}('{i}')" for i in ids)


def sql_pair_values(pairs, indent="    "):
    return ",\n".join(f"{indent}('{i}', '{t}')" for i, t in pairs)


COMMON_CHECK_HELPERS = """\
  -- Exact link-set comparison helper pattern: rows in one set but not the other.
"""


def render_migration(a, keepers, leavers):
    uuid = a["category_uuid"]
    f, t = a["rename"]["from"], a["rename"]["to"]
    return f"""-- Rename the 'skills-canada' category to 'skilled-trades' (client-approved).
-- Decisions: scripts/data/category-migrations/skills-canada-to-skilled-trades.json
-- (sheet {a['source']['sheet_id']}, modified {a['source']['sheet_modified_time']}).
-- 101 videos keep the renamed category; 59 lose only that link (their approved
-- path is already their live topical tag; nothing is inserted).
-- Generated by scripts/generate-skilled-trades-migration.py. Safe to re-run.
-- Rollback: scripts/data/rollbacks/rename_skills_canada_to_skilled_trades_rollback.sql

do $$
declare
  expected_id constant uuid := '{uuid}';
  sc_id uuid;
  st_id uuid;
  bad text[];
  n int;
  pre_categorized int;
  post_categorized int;
begin
  create temp table st_keepers (content_id text primary key) on commit drop;
  insert into st_keepers (content_id) values
{sql_id_values(keepers)};

  create temp table st_leavers (content_id text primary key, target_slug text not null) on commit drop;
  insert into st_leavers (content_id, target_slug) values
{sql_pair_values(leavers)};

  if (select count(*) from st_keepers) <> 101 then
    raise exception 'expected 101 keepers';
  end if;
  if (select count(*) from st_leavers) <> 59 then
    raise exception 'expected 59 leavers';
  end if;
  if exists (select 1 from st_keepers k join st_leavers l using (content_id)) then
    raise exception 'keeper/leaver overlap';
  end if;

  select id into sc_id from public.categories where slug = '{f['slug']}';
  select id into st_id from public.categories where slug = '{t['slug']}';

  if st_id is not null and sc_id is null then
    -- Terminal state: validate the approved outcome against exact IDs, then no-op.
    if st_id <> expected_id then
      raise exception 'skilled-trades exists with unexpected id %', st_id;
    end if;
    perform 1 from public.categories
      where id = expected_id and slug = '{t['slug']}' and name = '{t['name']}'
        and icon = '{t['icon']}' and display_order = {t['display_order']};
    if not found then
      raise exception 'skilled-trades category fields differ from approved state';
    end if;

    select array_agg(k.content_id order by k.content_id) into bad
    from st_keepers k
    where not exists (select 1 from public.content_categories cc
                      where cc.content_id = k.content_id and cc.category_id = expected_id);
    if bad is not null then
      raise exception 'terminal state: keepers missing skilled-trades link: %', array_to_string(bad, ', ');
    end if;

    select array_agg(cc.content_id order by cc.content_id) into bad
    from public.content_categories cc
    where cc.category_id = expected_id
      and not exists (select 1 from st_keepers k where k.content_id = cc.content_id);
    if bad is not null then
      raise exception 'terminal state: unexpected skilled-trades links: %', array_to_string(bad, ', ');
    end if;

    select array_agg(l.content_id order by l.content_id) into bad
    from st_leavers l
    where not exists (
      select 1 from public.content_categories cc
      join public.categories c on c.id = cc.category_id
      where cc.content_id = l.content_id and c.slug = l.target_slug
    );
    if bad is not null then
      raise exception 'terminal state: leavers missing topical target: %', array_to_string(bad, ', ');
    end if;

    raise notice 'skills-canada -> skilled-trades already applied; terminal state validated';
    return;
  end if;

  if sc_id is null then
    raise exception 'skills-canada category not found and skilled-trades not in terminal state';
  end if;
  if st_id is not null then
    raise exception 'both skills-canada and skilled-trades categories exist; manual repair required';
  end if;
  if sc_id <> expected_id then
    raise exception 'skills-canada has unexpected id % (expected %)', sc_id, expected_id;
  end if;

  perform 1 from public.categories
    where id = expected_id and name = '{f['name']}' and icon = '{f['icon']}'
      and display_order = {f['display_order']};
  if not found then
    raise exception 'skills-canada category fields differ from expected pre-state';
  end if;

  -- The complete skills-canada link set must be exactly keepers + leavers (001..160).
  select array_agg(x.content_id order by x.content_id) into bad
  from (select content_id from st_keepers union select content_id from st_leavers) x
  where not exists (select 1 from public.content_categories cc
                    where cc.content_id = x.content_id and cc.category_id = expected_id);
  if bad is not null then
    raise exception 'expected skills-canada links missing for: %', array_to_string(bad, ', ');
  end if;

  select array_agg(cc.content_id order by cc.content_id) into bad
  from public.content_categories cc
  where cc.category_id = expected_id
    and not exists (select 1 from (select content_id from st_keepers
                                   union select content_id from st_leavers) x
                    where x.content_id = cc.content_id);
  if bad is not null then
    raise exception 'unexpected skills-canada links for: %', array_to_string(bad, ', ');
  end if;

  -- Every leaver must already carry its approved topical tag (nothing is inserted).
  select array_agg(l.content_id order by l.content_id) into bad
  from st_leavers l
  where not exists (
    select 1 from public.content_categories cc
    join public.categories c on c.id = cc.category_id
    where cc.content_id = l.content_id and c.slug = l.target_slug
  );
  if bad is not null then
    raise exception 'leavers missing approved topical tag: %', array_to_string(bad, ', ');
  end if;

  select count(distinct cc.content_id) into pre_categorized
  from public.content_categories cc
  join public.content ct on ct.id = cc.content_id
  where ct.is_published and ct.content_type = 'video';

  delete from public.content_categories cc
  using st_leavers l
  where cc.content_id = l.content_id and cc.category_id = expected_id;
  get diagnostics n = row_count;
  if n <> 59 then
    raise exception 'expected to delete 59 skills-canada links, deleted %', n;
  end if;

  update public.categories
  set slug = '{t['slug']}', name = '{t['name']}', icon = '{t['icon']}'
  where id = expected_id;
  get diagnostics n = row_count;
  if n <> 1 then
    raise exception 'expected to rename 1 category row, updated %', n;
  end if;

  -- Postconditions.
  if exists (select 1 from public.categories where slug = '{f['slug']}') then
    raise exception 'a skills-canada category row still exists';
  end if;

  select array_agg(k.content_id order by k.content_id) into bad
  from st_keepers k
  where not exists (select 1 from public.content_categories cc
                    where cc.content_id = k.content_id and cc.category_id = expected_id);
  if bad is not null then
    raise exception 'keepers missing skilled-trades link after rename: %', array_to_string(bad, ', ');
  end if;

  select array_agg(cc.content_id order by cc.content_id) into bad
  from public.content_categories cc
  where cc.category_id = expected_id
    and not exists (select 1 from st_keepers k where k.content_id = cc.content_id);
  if bad is not null then
    raise exception 'unexpected skilled-trades links after rename: %', array_to_string(bad, ', ');
  end if;

  select array_agg(l.content_id order by l.content_id) into bad
  from st_leavers l
  where not exists (select 1 from public.content_categories cc where cc.content_id = l.content_id);
  if bad is not null then
    raise exception 'leavers left with no category: %', array_to_string(bad, ', ');
  end if;

  select count(distinct cc.content_id) into post_categorized
  from public.content_categories cc
  join public.content ct on ct.id = cc.content_id
  where ct.is_published and ct.content_type = 'video';
  if post_categorized <> pre_categorized then
    raise exception 'categorized published-video count changed: % -> %', pre_categorized, post_categorized;
  end if;

  raise notice 'renamed skills-canada -> skilled-trades; 101 keepers, 59 links removed';
end $$;
"""


def render_rollback(a, keepers, leavers):
    uuid = a["category_uuid"]
    f, t = a["rename"]["from"], a["rename"]["to"]
    all_ids = sorted(keepers + [i for i, _ in leavers])
    return f"""-- Rollback for 20260805210000_rename_skills_canada_to_skilled_trades.sql.
-- Renames the category back and reinserts the 59 removed links.
-- Generated by scripts/generate-skilled-trades-migration.py. Safe to re-run.
-- Full behavioral rollback also requires redeploying the previous app commit
-- and invalidating the content cache; see the migration plan runbook.

do $$
declare
  expected_id constant uuid := '{uuid}';
  sc_id uuid;
  st_id uuid;
  bad text[];
  n int;
begin
  create temp table sc_all_links (content_id text primary key) on commit drop;
  insert into sc_all_links (content_id) values
{sql_id_values(all_ids)};

  create temp table sc_reinsert (content_id text primary key) on commit drop;
  insert into sc_reinsert (content_id) values
{sql_id_values(sorted(i for i, _ in leavers))};

  select id into sc_id from public.categories where slug = '{f['slug']}';
  select id into st_id from public.categories where slug = '{t['slug']}';

  if sc_id is not null and st_id is not null then
    raise exception 'both skills-canada and skilled-trades exist; manual repair required';
  end if;
  if sc_id is null and st_id is null then
    raise exception 'neither skills-canada nor skilled-trades exists; manual repair required';
  end if;
  if coalesce(sc_id, st_id) <> expected_id then
    raise exception 'category slug belongs to unexpected id % (expected %)', coalesce(sc_id, st_id), expected_id;
  end if;

  if st_id is not null then
    -- Execute the rollback.
    update public.categories
    set slug = '{f['slug']}', name = '{f['name']}', icon = '{f['icon']}',
        display_order = {f['display_order']}
    where id = expected_id;
    get diagnostics n = row_count;
    if n <> 1 then
      raise exception 'expected to rename 1 category row, updated %', n;
    end if;

    insert into public.content_categories (content_id, category_id)
    select r.content_id, expected_id from sc_reinsert r
    on conflict (content_id, category_id) do nothing;
  else
    raise notice 'skills-canada already present; validating rolled-back state';
    perform 1 from public.categories
      where id = expected_id and name = '{f['name']}' and icon = '{f['icon']}'
        and display_order = {f['display_order']};
    if not found then
      raise exception 'skills-canada category fields differ from original state';
    end if;
  end if;

  -- Final state (both branches): the exact original 160-link set.
  select array_agg(x.content_id order by x.content_id) into bad
  from sc_all_links x
  where not exists (select 1 from public.content_categories cc
                    where cc.content_id = x.content_id and cc.category_id = expected_id);
  if bad is not null then
    raise exception 'links missing after rollback: %', array_to_string(bad, ', ');
  end if;

  select array_agg(cc.content_id order by cc.content_id) into bad
  from public.content_categories cc
  where cc.category_id = expected_id
    and not exists (select 1 from sc_all_links x where x.content_id = cc.content_id);
  if bad is not null then
    raise exception 'unexpected links after rollback: %', array_to_string(bad, ', ');
  end if;

  raise notice 'rollback state verified: skills-canada with the original 160 links';
end $$;
"""


def main():
    artifact = json.load(open(ARTIFACT))
    keepers, leavers = validate(artifact)
    with open(MIGRATION, "w") as fh:
        fh.write(render_migration(artifact, keepers, leavers))
    with open(ROLLBACK, "w") as fh:
        fh.write(render_rollback(artifact, keepers, leavers))
    print(f"OK: wrote {os.path.relpath(MIGRATION, ROOT)} and {os.path.relpath(ROLLBACK, ROOT)}")
    print(f"    keepers={len(keepers)} leavers={len(leavers)}")


if __name__ == "__main__":
    main()
