-- Rollback for 20260805210000_rename_skills_canada_to_skilled_trades.sql.
-- Renames the category back and reinserts the 59 removed links.
-- Generated by scripts/generate-skilled-trades-migration.py. Safe to re-run.
-- Full behavioral rollback also requires redeploying the previous app commit
-- and invalidating the content cache; see the migration plan runbook.

do $$
declare
  expected_id constant uuid := '7cd3fa1b-ae72-4632-8fa5-c0d133b18802';
  sc_id uuid;
  st_id uuid;
  bad text[];
  n int;
begin
  create temp table sc_all_links (content_id text primary key) on commit drop;
  insert into sc_all_links (content_id) values
    ('skills-canada-001'),
    ('skills-canada-002'),
    ('skills-canada-003'),
    ('skills-canada-004'),
    ('skills-canada-005'),
    ('skills-canada-006'),
    ('skills-canada-007'),
    ('skills-canada-008'),
    ('skills-canada-009'),
    ('skills-canada-010'),
    ('skills-canada-011'),
    ('skills-canada-012'),
    ('skills-canada-013'),
    ('skills-canada-014'),
    ('skills-canada-015'),
    ('skills-canada-016'),
    ('skills-canada-017'),
    ('skills-canada-018'),
    ('skills-canada-019'),
    ('skills-canada-020'),
    ('skills-canada-021'),
    ('skills-canada-022'),
    ('skills-canada-023'),
    ('skills-canada-024'),
    ('skills-canada-025'),
    ('skills-canada-026'),
    ('skills-canada-027'),
    ('skills-canada-028'),
    ('skills-canada-029'),
    ('skills-canada-030'),
    ('skills-canada-031'),
    ('skills-canada-032'),
    ('skills-canada-033'),
    ('skills-canada-034'),
    ('skills-canada-035'),
    ('skills-canada-036'),
    ('skills-canada-037'),
    ('skills-canada-038'),
    ('skills-canada-039'),
    ('skills-canada-040'),
    ('skills-canada-041'),
    ('skills-canada-042'),
    ('skills-canada-043'),
    ('skills-canada-044'),
    ('skills-canada-045'),
    ('skills-canada-046'),
    ('skills-canada-047'),
    ('skills-canada-048'),
    ('skills-canada-049'),
    ('skills-canada-050'),
    ('skills-canada-051'),
    ('skills-canada-052'),
    ('skills-canada-053'),
    ('skills-canada-054'),
    ('skills-canada-055'),
    ('skills-canada-056'),
    ('skills-canada-057'),
    ('skills-canada-058'),
    ('skills-canada-059'),
    ('skills-canada-060'),
    ('skills-canada-061'),
    ('skills-canada-062'),
    ('skills-canada-063'),
    ('skills-canada-064'),
    ('skills-canada-065'),
    ('skills-canada-066'),
    ('skills-canada-067'),
    ('skills-canada-068'),
    ('skills-canada-069'),
    ('skills-canada-070'),
    ('skills-canada-071'),
    ('skills-canada-072'),
    ('skills-canada-073'),
    ('skills-canada-074'),
    ('skills-canada-075'),
    ('skills-canada-076'),
    ('skills-canada-077'),
    ('skills-canada-078'),
    ('skills-canada-079'),
    ('skills-canada-080'),
    ('skills-canada-081'),
    ('skills-canada-082'),
    ('skills-canada-083'),
    ('skills-canada-084'),
    ('skills-canada-085'),
    ('skills-canada-086'),
    ('skills-canada-087'),
    ('skills-canada-088'),
    ('skills-canada-089'),
    ('skills-canada-090'),
    ('skills-canada-091'),
    ('skills-canada-092'),
    ('skills-canada-093'),
    ('skills-canada-094'),
    ('skills-canada-095'),
    ('skills-canada-096'),
    ('skills-canada-097'),
    ('skills-canada-098'),
    ('skills-canada-099'),
    ('skills-canada-100'),
    ('skills-canada-101'),
    ('skills-canada-102'),
    ('skills-canada-103'),
    ('skills-canada-104'),
    ('skills-canada-105'),
    ('skills-canada-106'),
    ('skills-canada-107'),
    ('skills-canada-108'),
    ('skills-canada-109'),
    ('skills-canada-110'),
    ('skills-canada-111'),
    ('skills-canada-112'),
    ('skills-canada-113'),
    ('skills-canada-114'),
    ('skills-canada-115'),
    ('skills-canada-116'),
    ('skills-canada-117'),
    ('skills-canada-118'),
    ('skills-canada-119'),
    ('skills-canada-120'),
    ('skills-canada-121'),
    ('skills-canada-122'),
    ('skills-canada-123'),
    ('skills-canada-124'),
    ('skills-canada-125'),
    ('skills-canada-126'),
    ('skills-canada-127'),
    ('skills-canada-128'),
    ('skills-canada-129'),
    ('skills-canada-130'),
    ('skills-canada-131'),
    ('skills-canada-132'),
    ('skills-canada-133'),
    ('skills-canada-134'),
    ('skills-canada-135'),
    ('skills-canada-136'),
    ('skills-canada-137'),
    ('skills-canada-138'),
    ('skills-canada-139'),
    ('skills-canada-140'),
    ('skills-canada-141'),
    ('skills-canada-142'),
    ('skills-canada-143'),
    ('skills-canada-144'),
    ('skills-canada-145'),
    ('skills-canada-146'),
    ('skills-canada-147'),
    ('skills-canada-148'),
    ('skills-canada-149'),
    ('skills-canada-150'),
    ('skills-canada-151'),
    ('skills-canada-152'),
    ('skills-canada-153'),
    ('skills-canada-154'),
    ('skills-canada-155'),
    ('skills-canada-156'),
    ('skills-canada-157'),
    ('skills-canada-158'),
    ('skills-canada-159'),
    ('skills-canada-160');

  create temp table sc_reinsert (content_id text primary key) on commit drop;
  insert into sc_reinsert (content_id) values
    ('skills-canada-005'),
    ('skills-canada-014'),
    ('skills-canada-015'),
    ('skills-canada-016'),
    ('skills-canada-017'),
    ('skills-canada-018'),
    ('skills-canada-019'),
    ('skills-canada-023'),
    ('skills-canada-024'),
    ('skills-canada-025'),
    ('skills-canada-026'),
    ('skills-canada-027'),
    ('skills-canada-031'),
    ('skills-canada-032'),
    ('skills-canada-033'),
    ('skills-canada-053'),
    ('skills-canada-054'),
    ('skills-canada-065'),
    ('skills-canada-066'),
    ('skills-canada-067'),
    ('skills-canada-068'),
    ('skills-canada-078'),
    ('skills-canada-081'),
    ('skills-canada-085'),
    ('skills-canada-091'),
    ('skills-canada-102'),
    ('skills-canada-103'),
    ('skills-canada-104'),
    ('skills-canada-113'),
    ('skills-canada-114'),
    ('skills-canada-118'),
    ('skills-canada-119'),
    ('skills-canada-120'),
    ('skills-canada-121'),
    ('skills-canada-122'),
    ('skills-canada-123'),
    ('skills-canada-124'),
    ('skills-canada-125'),
    ('skills-canada-127'),
    ('skills-canada-135'),
    ('skills-canada-136'),
    ('skills-canada-137'),
    ('skills-canada-138'),
    ('skills-canada-139'),
    ('skills-canada-140'),
    ('skills-canada-141'),
    ('skills-canada-142'),
    ('skills-canada-143'),
    ('skills-canada-145'),
    ('skills-canada-147'),
    ('skills-canada-148'),
    ('skills-canada-149'),
    ('skills-canada-150'),
    ('skills-canada-151'),
    ('skills-canada-152'),
    ('skills-canada-153'),
    ('skills-canada-154'),
    ('skills-canada-159'),
    ('skills-canada-160');

  select id into sc_id from public.categories where slug = 'skills-canada';
  select id into st_id from public.categories where slug = 'skilled-trades';

  if sc_id is not null and st_id is not null then
    raise exception 'both skills-canada and skilled-trades exist; manual repair required';
  end if;
  if sc_id is null and st_id is null then
    raise exception 'neither skills-canada nor skilled-trades exists; manual repair required';
  end if;
  if coalesce(sc_id, st_id) <> expected_id then
    raise exception 'category slug belongs to unexpected id % (expected %)', coalesce(sc_id, st_id), expected_id;
  end if;

  if st_id is not null then
    -- Execute the rollback.
    update public.categories
    set slug = 'skills-canada', name = 'Skills Canada', icon = 'Trophy',
        display_order = 0
    where id = expected_id;
    get diagnostics n = row_count;
    if n <> 1 then
      raise exception 'expected to rename 1 category row, updated %', n;
    end if;

    insert into public.content_categories (content_id, category_id)
    select r.content_id, expected_id from sc_reinsert r
    on conflict (content_id, category_id) do nothing;
  else
    raise notice 'skills-canada already present; validating rolled-back state';
    perform 1 from public.categories
      where id = expected_id and name = 'Skills Canada' and icon = 'Trophy'
        and display_order = 0;
    if not found then
      raise exception 'skills-canada category fields differ from original state';
    end if;
  end if;

  -- Final state (both branches): the exact original 160-link set.
  select array_agg(x.content_id order by x.content_id) into bad
  from sc_all_links x
  where not exists (select 1 from public.content_categories cc
                    where cc.content_id = x.content_id and cc.category_id = expected_id);
  if bad is not null then
    raise exception 'links missing after rollback: %', array_to_string(bad, ', ');
  end if;

  select array_agg(cc.content_id order by cc.content_id) into bad
  from public.content_categories cc
  where cc.category_id = expected_id
    and not exists (select 1 from sc_all_links x where x.content_id = cc.content_id);
  if bad is not null then
    raise exception 'unexpected links after rollback: %', array_to_string(bad, ', ');
  end if;

  raise notice 'rollback state verified: skills-canada with the original 160 links';
end $$;
