-- Backfill reflection for the 17 'long-term-care' rows.
-- Generated by scripts/generate-reflections-migration.py from scripts/data/reflections/long-term-care.json.
-- Targets rows by stable id. Fails the transaction if the expected row
-- count is not updated.

do $$
declare
  expected_count int := 17;
  actual_count int;
begin
  with v(id, new_reflection) as (values
      ('ltc-careers-001', 'Health care can mean clinical work, but it can also mean the meal that gets to someone at the right time. As you think about your own future, what kind of impact do you want your daily work to have on the people around you?'),
      ('ltc-careers-002', 'Some careers ask you to choose between technical skill and close human connection. As you think about life after high school, would you rather a role that grows your expertise quickly, one that grows your relationships slowly, or both at the same time?'),
      ('ltc-careers-003', 'We do not always picture creativity inside a hospital or care home. As you think about your own next step, where do you want your creativity to live, and what kind of place do you imagine making it useful?'),
      ('ltc-careers-004', 'Most meals you eat are made by a team you never see. As you think about the work you might do after high school, what would it feel like to be on the side of the counter where someone else''s dignity is part of your job?'),
      ('ltc-careers-005', 'Independence is something most of us take for granted until we start losing it. As you think about your own life after high school, what would it look like to help someone else hold on to theirs, and would that kind of work appeal to you?'),
      ('ltc-careers-006', 'It is easy to overlook the jobs that keep places safe and livable. As you imagine your future workplace, what would it mean to take pride in work that is mostly invisible until it stops happening?'),
      ('ltc-careers-007', 'Some careers exist for the hardest moments in other people''s lives. As you think about life after high school, do you want a job that meets people on their best days, their worst days, or somewhere in between?'),
      ('ltc-careers-008', 'Art and health care do not always feel like they belong in the same conversation. As you think about what you are good at, what would it look like to use a creative skill of yours in a job that helps someone else?'),
      ('ltc-careers-009', 'Trust is usually built in small, repeated moments, not in big ones. As you imagine your own first job after high school, where would you want to be the person who shows up consistently enough to actually be trusted?'),
      ('ltc-careers-010', 'Not every health care career starts with years of school. As you think about your own pace, would you rather find a hands-on entry point quickly and grow from there, or take a longer route through more training first?'),
      ('ltc-careers-011', 'Some jobs hide their impact for months; others let you feel it inside one shift. As you imagine your future work, how soon do you want to be able to see the difference you are making?'),
      ('ltc-careers-012', 'Careers do not have to stay flat. As you think about your own future five or ten years out, do you imagine yourself going deeper into one specialty, moving into leadership, or staying close to the people you started serving?'),
      ('ltc-careers-013', 'Big places only work because someone is balancing a lot of competing needs at once. As you picture your own working life, would you rather be the one delivering the care directly, or the one keeping the whole place running?'),
      ('ltc-careers-014', 'Some careers reward people who like complexity. As you think about what kind of problems you want to spend years getting good at, would you rather work on questions with clean answers or on questions where the answer keeps shifting?'),
      ('ltc-careers-015', 'Many careers look smaller from the outside than they actually are. As you start considering your own path, what would it change if you knew a role you thought of as one job could expand into something much bigger?'),
      ('ltc-careers-016', 'School often grades you on individual work, but most jobs grade you on what your team does together. As you think about your strengths, what kind of teammate do you want to be known as in your first real role?'),
      ('ltc-careers-017', 'Critical thinking is not just for tests. As you think about the kind of work you want to do, where would you rather be making careful, small judgments all day: in front of a screen, on a worksite, or alongside other people?')
  )
  update public.content c
  set reflection = v.new_reflection
  from v
  where c.id = v.id;

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
