-- Rename the 'skills-canada' category to 'skilled-trades' (client-approved).
-- Decisions: scripts/data/category-migrations/skills-canada-to-skilled-trades.json
-- (sheet 1Y4qXlCn6q0chqyp7r-r2IB95MQ2eTOqpxQR9pjd8TPQ, modified 2026-08-05T20:45:28.505Z).
-- 101 videos keep the renamed category; 59 lose only that link (their approved
-- path is already their live topical tag; nothing is inserted).
-- Generated by scripts/generate-skilled-trades-migration.py. Safe to re-run.
-- Rollback: scripts/data/rollbacks/rename_skills_canada_to_skilled_trades_rollback.sql

do $$
declare
  expected_id constant uuid := '7cd3fa1b-ae72-4632-8fa5-c0d133b18802';
  sc_id uuid;
  st_id uuid;
  bad text[];
  n int;
  pre_categorized int;
  post_categorized int;
begin
  create temp table st_keepers (content_id text primary key) on commit drop;
  insert into st_keepers (content_id) values
    ('skills-canada-001'),
    ('skills-canada-002'),
    ('skills-canada-003'),
    ('skills-canada-004'),
    ('skills-canada-006'),
    ('skills-canada-007'),
    ('skills-canada-008'),
    ('skills-canada-009'),
    ('skills-canada-010'),
    ('skills-canada-011'),
    ('skills-canada-012'),
    ('skills-canada-013'),
    ('skills-canada-020'),
    ('skills-canada-021'),
    ('skills-canada-022'),
    ('skills-canada-028'),
    ('skills-canada-029'),
    ('skills-canada-030'),
    ('skills-canada-034'),
    ('skills-canada-035'),
    ('skills-canada-036'),
    ('skills-canada-037'),
    ('skills-canada-038'),
    ('skills-canada-039'),
    ('skills-canada-040'),
    ('skills-canada-041'),
    ('skills-canada-042'),
    ('skills-canada-043'),
    ('skills-canada-044'),
    ('skills-canada-045'),
    ('skills-canada-046'),
    ('skills-canada-047'),
    ('skills-canada-048'),
    ('skills-canada-049'),
    ('skills-canada-050'),
    ('skills-canada-051'),
    ('skills-canada-052'),
    ('skills-canada-055'),
    ('skills-canada-056'),
    ('skills-canada-057'),
    ('skills-canada-058'),
    ('skills-canada-059'),
    ('skills-canada-060'),
    ('skills-canada-061'),
    ('skills-canada-062'),
    ('skills-canada-063'),
    ('skills-canada-064'),
    ('skills-canada-069'),
    ('skills-canada-070'),
    ('skills-canada-071'),
    ('skills-canada-072'),
    ('skills-canada-073'),
    ('skills-canada-074'),
    ('skills-canada-075'),
    ('skills-canada-076'),
    ('skills-canada-077'),
    ('skills-canada-079'),
    ('skills-canada-080'),
    ('skills-canada-082'),
    ('skills-canada-083'),
    ('skills-canada-084'),
    ('skills-canada-086'),
    ('skills-canada-087'),
    ('skills-canada-088'),
    ('skills-canada-089'),
    ('skills-canada-090'),
    ('skills-canada-092'),
    ('skills-canada-093'),
    ('skills-canada-094'),
    ('skills-canada-095'),
    ('skills-canada-096'),
    ('skills-canada-097'),
    ('skills-canada-098'),
    ('skills-canada-099'),
    ('skills-canada-100'),
    ('skills-canada-101'),
    ('skills-canada-105'),
    ('skills-canada-106'),
    ('skills-canada-107'),
    ('skills-canada-108'),
    ('skills-canada-109'),
    ('skills-canada-110'),
    ('skills-canada-111'),
    ('skills-canada-112'),
    ('skills-canada-115'),
    ('skills-canada-116'),
    ('skills-canada-117'),
    ('skills-canada-126'),
    ('skills-canada-128'),
    ('skills-canada-129'),
    ('skills-canada-130'),
    ('skills-canada-131'),
    ('skills-canada-132'),
    ('skills-canada-133'),
    ('skills-canada-134'),
    ('skills-canada-144'),
    ('skills-canada-146'),
    ('skills-canada-155'),
    ('skills-canada-156'),
    ('skills-canada-157'),
    ('skills-canada-158');

  create temp table st_leavers (content_id text primary key, target_slug text not null) on commit drop;
  insert into st_leavers (content_id, target_slug) values
    ('skills-canada-005', 'on-the-job'),
    ('skills-canada-014', 'how-i-got-here'),
    ('skills-canada-015', 'on-the-job'),
    ('skills-canada-016', 'how-i-got-here'),
    ('skills-canada-017', 'post-secondary'),
    ('skills-canada-018', 'on-the-job'),
    ('skills-canada-019', 'on-the-job'),
    ('skills-canada-023', 'how-i-got-here'),
    ('skills-canada-024', 'on-the-job'),
    ('skills-canada-025', 'how-i-got-here'),
    ('skills-canada-026', 'on-the-job'),
    ('skills-canada-027', 'how-i-got-here'),
    ('skills-canada-031', 'problems-to-solve'),
    ('skills-canada-032', 'on-the-job'),
    ('skills-canada-033', 'emerging-careers'),
    ('skills-canada-053', 'post-secondary'),
    ('skills-canada-054', 'on-the-job'),
    ('skills-canada-065', 'emerging-careers'),
    ('skills-canada-066', 'emerging-careers'),
    ('skills-canada-067', 'mindsets'),
    ('skills-canada-068', 'on-the-job'),
    ('skills-canada-078', 'mindsets'),
    ('skills-canada-081', 'emerging-careers'),
    ('skills-canada-085', 'on-the-job'),
    ('skills-canada-091', 'how-i-got-here'),
    ('skills-canada-102', 'on-the-job'),
    ('skills-canada-103', 'on-the-job'),
    ('skills-canada-104', 'on-the-job'),
    ('skills-canada-113', 'emerging-careers'),
    ('skills-canada-114', 'emerging-careers'),
    ('skills-canada-118', 'life-skills'),
    ('skills-canada-119', 'life-skills'),
    ('skills-canada-120', 'life-skills'),
    ('skills-canada-121', 'how-i-got-here'),
    ('skills-canada-122', 'how-i-got-here'),
    ('skills-canada-123', 'on-the-job'),
    ('skills-canada-124', 'post-secondary'),
    ('skills-canada-125', 'on-the-job'),
    ('skills-canada-127', 'post-secondary'),
    ('skills-canada-135', 'emerging-careers'),
    ('skills-canada-136', 'problems-to-solve'),
    ('skills-canada-137', 'post-secondary'),
    ('skills-canada-138', 'on-the-job'),
    ('skills-canada-139', 'on-the-job'),
    ('skills-canada-140', 'on-the-job'),
    ('skills-canada-141', 'on-the-job'),
    ('skills-canada-142', 'how-i-got-here'),
    ('skills-canada-143', 'on-the-job'),
    ('skills-canada-145', 'on-the-job'),
    ('skills-canada-147', 'on-the-job'),
    ('skills-canada-148', 'on-the-job'),
    ('skills-canada-149', 'how-i-got-here'),
    ('skills-canada-150', 'post-secondary'),
    ('skills-canada-151', 'on-the-job'),
    ('skills-canada-152', 'on-the-job'),
    ('skills-canada-153', 'on-the-job'),
    ('skills-canada-154', 'problems-to-solve'),
    ('skills-canada-159', 'life-skills'),
    ('skills-canada-160', 'life-skills');

  if (select count(*) from st_keepers) <> 101 then
    raise exception 'expected 101 keepers';
  end if;
  if (select count(*) from st_leavers) <> 59 then
    raise exception 'expected 59 leavers';
  end if;
  if exists (select 1 from st_keepers k join st_leavers l using (content_id)) then
    raise exception 'keeper/leaver overlap';
  end if;

  select id into sc_id from public.categories where slug = 'skills-canada';
  select id into st_id from public.categories where slug = 'skilled-trades';

  if st_id is not null and sc_id is null then
    -- Terminal state: validate the approved outcome against exact IDs, then no-op.
    if st_id <> expected_id then
      raise exception 'skilled-trades exists with unexpected id %', st_id;
    end if;
    perform 1 from public.categories
      where id = expected_id and slug = 'skilled-trades' and name = 'Skilled Trades'
        and icon = 'Wrench' and display_order = 0;
    if not found then
      raise exception 'skilled-trades category fields differ from approved state';
    end if;

    select array_agg(k.content_id order by k.content_id) into bad
    from st_keepers k
    where not exists (select 1 from public.content_categories cc
                      where cc.content_id = k.content_id and cc.category_id = expected_id);
    if bad is not null then
      raise exception 'terminal state: keepers missing skilled-trades link: %', array_to_string(bad, ', ');
    end if;

    select array_agg(cc.content_id order by cc.content_id) into bad
    from public.content_categories cc
    where cc.category_id = expected_id
      and not exists (select 1 from st_keepers k where k.content_id = cc.content_id);
    if bad is not null then
      raise exception 'terminal state: unexpected skilled-trades links: %', array_to_string(bad, ', ');
    end if;

    select array_agg(l.content_id order by l.content_id) into bad
    from st_leavers l
    where not exists (
      select 1 from public.content_categories cc
      join public.categories c on c.id = cc.category_id
      where cc.content_id = l.content_id and c.slug = l.target_slug
    );
    if bad is not null then
      raise exception 'terminal state: leavers missing topical target: %', array_to_string(bad, ', ');
    end if;

    raise notice 'skills-canada -> skilled-trades already applied; terminal state validated';
    return;
  end if;

  if sc_id is null then
    raise exception 'skills-canada category not found and skilled-trades not in terminal state';
  end if;
  if st_id is not null then
    raise exception 'both skills-canada and skilled-trades categories exist; manual repair required';
  end if;
  if sc_id <> expected_id then
    raise exception 'skills-canada has unexpected id % (expected %)', sc_id, expected_id;
  end if;

  perform 1 from public.categories
    where id = expected_id and name = 'Skills Canada' and icon = 'Trophy'
      and display_order = 0;
  if not found then
    raise exception 'skills-canada category fields differ from expected pre-state';
  end if;

  -- The complete skills-canada link set must be exactly keepers + leavers (001..160).
  select array_agg(x.content_id order by x.content_id) into bad
  from (select content_id from st_keepers union select content_id from st_leavers) x
  where not exists (select 1 from public.content_categories cc
                    where cc.content_id = x.content_id and cc.category_id = expected_id);
  if bad is not null then
    raise exception 'expected skills-canada links missing for: %', array_to_string(bad, ', ');
  end if;

  select array_agg(cc.content_id order by cc.content_id) into bad
  from public.content_categories cc
  where cc.category_id = expected_id
    and not exists (select 1 from (select content_id from st_keepers
                                   union select content_id from st_leavers) x
                    where x.content_id = cc.content_id);
  if bad is not null then
    raise exception 'unexpected skills-canada links for: %', array_to_string(bad, ', ');
  end if;

  -- Every leaver must already carry its approved topical tag (nothing is inserted).
  select array_agg(l.content_id order by l.content_id) into bad
  from st_leavers l
  where not exists (
    select 1 from public.content_categories cc
    join public.categories c on c.id = cc.category_id
    where cc.content_id = l.content_id and c.slug = l.target_slug
  );
  if bad is not null then
    raise exception 'leavers missing approved topical tag: %', array_to_string(bad, ', ');
  end if;

  select count(distinct cc.content_id) into pre_categorized
  from public.content_categories cc
  join public.content ct on ct.id = cc.content_id
  where ct.is_published and ct.content_type = 'video';

  delete from public.content_categories cc
  using st_leavers l
  where cc.content_id = l.content_id and cc.category_id = expected_id;
  get diagnostics n = row_count;
  if n <> 59 then
    raise exception 'expected to delete 59 skills-canada links, deleted %', n;
  end if;

  update public.categories
  set slug = 'skilled-trades', name = 'Skilled Trades', icon = 'Wrench'
  where id = expected_id;
  get diagnostics n = row_count;
  if n <> 1 then
    raise exception 'expected to rename 1 category row, updated %', n;
  end if;

  -- Postconditions.
  if exists (select 1 from public.categories where slug = 'skills-canada') then
    raise exception 'a skills-canada category row still exists';
  end if;

  select array_agg(k.content_id order by k.content_id) into bad
  from st_keepers k
  where not exists (select 1 from public.content_categories cc
                    where cc.content_id = k.content_id and cc.category_id = expected_id);
  if bad is not null then
    raise exception 'keepers missing skilled-trades link after rename: %', array_to_string(bad, ', ');
  end if;

  select array_agg(cc.content_id order by cc.content_id) into bad
  from public.content_categories cc
  where cc.category_id = expected_id
    and not exists (select 1 from st_keepers k where k.content_id = cc.content_id);
  if bad is not null then
    raise exception 'unexpected skilled-trades links after rename: %', array_to_string(bad, ', ');
  end if;

  select array_agg(l.content_id order by l.content_id) into bad
  from st_leavers l
  where not exists (select 1 from public.content_categories cc where cc.content_id = l.content_id);
  if bad is not null then
    raise exception 'leavers left with no category: %', array_to_string(bad, ', ');
  end if;

  select count(distinct cc.content_id) into post_categorized
  from public.content_categories cc
  join public.content ct on ct.id = cc.content_id
  where ct.is_published and ct.content_type = 'video';
  if post_categorized <> pre_categorized then
    raise exception 'categorized published-video count changed: % -> %', pre_categorized, post_categorized;
  end if;

  raise notice 'renamed skills-canada -> skilled-trades; 101 keepers, 59 links removed';
end $$;
