-- Backfill reflection for the 61 'skills-canada-on-the-job' rows.
-- Generated by scripts/generate-reflections-migration.py from scripts/data/reflections/skills-canada-on-the-job.json.
-- Targets rows by stable id. Fails the transaction if the expected row
-- count is not updated.

do $$
declare
  expected_count int := 61;
  actual_count int;
begin
  with v(id, new_reflection) as (values
      ('skills-canada-004', 'Some jobs measure progress in episodes shipped, not objects kept. As you think about your own work style, would you find satisfaction in a fast cycle where everything is rebuilt next week, or in a slower one where what you make sticks around?'),
      ('skills-canada-005', 'Some jobs have a predictable last-mile crunch every cycle. As you imagine your own work, would you accept regular high-intensity finishes as the price of the job, or would that feel like a deal you would not make twice?'),
      ('skills-canada-011', 'Big projects come with logistics most clients never see. As you think about a job you might want to run yourself one day, where do you trust your instincts more: the visible work, or the invisible planning?'),
      ('skills-canada-012', 'Watching real workers document their day is a skill of its own. As you think about a career you are curious about, where would you look online to find someone showing what their work actually feels like, not just what it looks like?'),
      ('skills-canada-015', 'Tool choice in creative work is often a creative decision dressed up as a technical one. As you think about your own setup, do you pick what is industry-standard, or what fits how you actually work?'),
      ('skills-canada-018', 'Some creative careers grow through small public moments that compound. As you think about a craft of yours, where could you show up in front of even a few people this season, even if it feels low-stakes?'),
      ('skills-canada-019', 'Most creative jobs are more logistics than creativity once you are inside them. As you think about a creative path you want, would you still pick it knowing most days were production, sourcing, or scheduling instead of design?'),
      ('skills-canada-021', 'Some careers ask you to live on a schedule the rest of the world does not. As you think about your own future, could you imagine starting a workday before most of your friends are awake, every day, for years?'),
      ('skills-canada-022', 'Some jobs are quietly athletic. As you think about a craft you are drawn to, are you treating the physical side as part of the work itself, or as a side effect you would deal with later?'),
      ('skills-canada-024', 'Some jobs reward people who can hold focus when everyone else is distracted. As you think about a kind of work you might do, where would you want your concentration to be most useful: in calm conditions or in chaotic ones?'),
      ('skills-canada-026', 'The glamorous days in a creative job are usually the rare ones. As you think about a creative career you want, would you still pick it knowing most days were prep, edit, and email instead of the shoot?'),
      ('skills-canada-029', 'Some jobs ask you to stay alert during long quiet stretches. As you think about your own attention, would you do better in a role with constant action, or in one where the skill is catching small problems during slow runs?'),
      ('skills-canada-030', 'Some careers reward people who like the feedback loop between a program and a finished part. As you think about your own preferences, do you enjoy the moment when an idea becomes a physical thing more than the moment you had the idea?'),
      ('skills-canada-032', 'Some jobs put you upstream of every other team''s work. As you think about your own appetite for influence, would you rather make decisions that affect every team downstream, or stay closer to the parts users see and touch?'),
      ('skills-canada-034', 'Some kitchens are unforgiving by design. As you think about your own appetite for intensity, would you trade comfort for skills that hold up anywhere, or would you rather grow more slowly in calmer conditions?'),
      ('skills-canada-037', 'Some careers depend on the same clients coming back over years. As you think about your own people skills, would you rather get good at impressing strangers quickly, or get good at being someone people want to return to?'),
      ('skills-canada-038', 'Some careers grow by turning first visits into long-term relationships. As you think about your own consistency, do you keep up small habits over years, or do you start strong and let things drift?'),
      ('skills-canada-043', 'Some jobs ask you to learn by watching for the first year. As you think about your own patience, can you stay engaged when you are not the one doing the task, knowing it pays off later?'),
      ('skills-canada-044', 'Some fundamentals carry across every specialty in a trade. As you think about your own learning style, would you rather master the basics deeply once, or learn enough to specialize quickly and fill in gaps later?'),
      ('skills-canada-047', 'Some careers turn flat materials into three-dimensional objects in a few hours. As you think about what kinds of progress satisfy you, would you rather watch a shape emerge in front of you, or finish something on a screen?'),
      ('skills-canada-048', 'Some trades pay people willing to travel to where the work is. As you think about your own roots, what would it mean to live closer to a job than to a hometown for stretches of your career?'),
      ('skills-canada-049', 'Some jobs make sense only when you can see the whole connected system. As you think about your own way of working, do you prefer pieces that you finish discretely, or work that lives inside a bigger network of parts?'),
      ('skills-canada-052', 'Some production jobs measure you on quantity and quality at the same time. As you think about your own habits, can you keep both bars high under pressure, or does one tend to slip when you are tired?'),
      ('skills-canada-054', 'Some careers reward detail-oriented people more than creative ones. As you think about your own strengths, do you find more satisfaction in being precise inside a system, or in coming up with the system to begin with?'),
      ('skills-canada-057', 'Some union trades reward patience inside a structured ladder. As you think about your own appetite for structure, would you rather climb a clear path with predictable pay, or improvise your way up with bigger swings either direction?'),
      ('skills-canada-059', 'Some trades pay for systems that no one will see in action unless something goes wrong. As you think about your own pride in your work, would you be okay being invisible most of the time and critical occasionally?'),
      ('skills-canada-060', 'Some careers depend on staying calm when other people are panicked. As you think about your own response under pressure, can you find satisfaction in being the person who shows up at the worst moment and fixes the situation?'),
      ('skills-canada-063', 'Most trades build confidence through reps you have already watched many times. As you think about your own first job after high school, would you accept slow growth in exchange for quietly becoming competent, instead of being thrown in unprepared?'),
      ('skills-canada-064', 'Top-of-the-market careers in any trade run on reputation and very specific skills. As you think about a craft you might learn, what would it take to be one of the few who get paid for it, instead of one of the many?'),
      ('skills-canada-068', 'Visible technique in any craft sits on top of invisible reps. As you think about something you want to be good at, are you willing to put in the boring foundational work that nobody will see, before any flashy moves land?'),
      ('skills-canada-070', 'Some careers leave you with skills that hold up wherever you go next. As you think about a hard environment you might enter, would the lasting skills be worth the years inside it, even if you do not stay forever?'),
      ('skills-canada-071', 'Some careers ask you to switch between methodical and improvisational without losing focus. As you think about your own pace, do you prefer one steady mode, or are you energized by changing modes throughout the day?'),
      ('skills-canada-075', 'Some specialized work commands a premium because clients will pay for craftsmanship. As you think about a path you might take, would the patience to do something the old way appeal to you, knowing it would lead to higher-end clients?'),
      ('skills-canada-077', 'Some careers thrive on repetition. As you think about your own relationship to doing the same thing many times, does repetition feel like a chance to refine, or like a reason to look for something else?'),
      ('skills-canada-080', 'Some work blurs the line between trade and art. As you think about your own creative side, would it satisfy you to take days on something a casual viewer cannot tell apart from a faster, cheaper version?'),
      ('skills-canada-085', 'Some skills depend on noticing what is slightly off when everyone else is busy. As you think about your own attention, do you tend to scan for what is wrong, or trust that someone else will catch it before it becomes a problem?'),
      ('skills-canada-086', 'Some jobs are unglamorous but visible to everyone who works near you. As you think about your own ambition, would you take an early role known mostly to insiders, and trust that good prep work gets you noticed by the right people?'),
      ('skills-canada-090', 'Some trades cover so much ground that early specialization is the difference between average and exceptional. As you think about your own next step, what would it take to pick a niche on purpose, instead of arriving at one because of who hired you first?'),
      ('skills-canada-093', 'Some industries have a structural shortage that benefits people entering now. As you think about your own next step, what would change in your reasoning if you knew the pay reflected that shortage, and the shortage was not closing soon?'),
      ('skills-canada-102', 'Some careers ask you to balance enforcement with relationship-building. As you think about your own people skills, can you hold a hard line without making someone defensive, and would that combination feel like a strength of yours?'),
      ('skills-canada-103', 'Strong workplace safety is built more by social norms than by rules. As you think about your own influence on a group, are you the kind of person who can shift what coworkers expect of each other, or do you wait for someone else to set the tone?'),
      ('skills-canada-104', 'Some trainings only work as recurring habits, not as one-time check-ins. As you think about your own way of staying current, what would it take to treat learning as continuous, instead of as something you finish?'),
      ('skills-canada-108', 'Some trades are being reshaped by new materials and tech every few years. As you think about a career you might enter, would you trust yourself to stay current as the work changes, or would you prefer a craft that stays mostly the same?'),
      ('skills-canada-111', 'Some training programs land you straight into the companies that hired your classmates. As you think about a program you are considering, what would change if you chose the one with the strongest local employer pipeline, instead of the one with the best reputation?'),
      ('skills-canada-115', 'Some careers reward the discipline to stay alert during quiet stretches. As you think about a job you might do for years, where do you imagine your attention drifting, and what would help you catch the moments that matter?'),
      ('skills-canada-125', 'Some careers are quieter than you expect: more simulation, paperwork, and review meetings than physical prototypes. As you think about your own preferences, does that pace sound like the right tradeoff for the importance of the work, or like the wrong fit?'),
      ('skills-canada-128', 'Some trades have shifted from wrenches to laptops faster than students realize. As you think about a career you imagine being hands-on, what would change if much of it now happens at a screen, and would that be better or worse for you?'),
      ('skills-canada-129', 'Some careers are quietly seasonal, and people who thrive plan around the swings. As you think about your own appetite for variable pace, would you rather work steady year-round, or have busy seasons and slower ones in the same job?'),
      ('skills-canada-131', 'Some niches are well-defined and easy to enter while staying in steady demand. As you think about your own preferences, would you rather pick a smaller, well-defined field, or compete in a bigger, more crowded one?'),
      ('skills-canada-132', 'Watching mastery in any craft helps you calibrate your own bar. As you think about a craft you are trying to learn, where would you go to see what the high end actually looks like, before judging your own progress?'),
      ('skills-canada-133', 'Some fundamentals stay the same across every specialty in a trade. As you think about your own focus, would you rather get rock-solid on basics first, or learn the basics alongside one specific application from day one?'),
      ('skills-canada-134', 'Speed in any craft comes from foundational reps you cannot see. As you think about something you are starting from zero, are you willing to do the boring practice for months before any visible result?'),
      ('skills-canada-138', 'Some creative jobs are half production and half conversations about what to make. As you think about your own way of working, would you rather be left alone with the visual work, or in a constant back-and-forth with people about it?'),
      ('skills-canada-140', 'Most freelance careers are more business than craft after the first year. As you think about working for yourself, would you welcome the pricing, contracts, and client management as part of the job, or would that feel like overhead?'),
      ('skills-canada-143', 'Some jobs are long, iterative, and quiet. As you think about your own appetite for repetition, can you find satisfaction in watching the same five seconds of work until it looks right, or would that feel like a slow loop?'),
      ('skills-canada-146', 'Some careers sit between technician and engineer, where reading schematics and writing basic code both matter. As you think about your own skill mix, would you welcome a job that asks for both kinds of thinking, or would you rather lean fully into one?'),
      ('skills-canada-148', 'Big-company software jobs involve more meetings and review than students expect. As you think about your own focus, can you fit deep work between coordination, or would that fragmentation drain you over time?'),
      ('skills-canada-151', 'Some placements only pay off if you treat them like real jobs. As you think about your own approach to school work-terms, what would change if you assumed the people around you were assessing whether to hire you full-time?'),
      ('skills-canada-153', 'Some careers are about building the system; others are about operating it once it exists. As you think about your own preferences, would you rather design the line, or run it well every day after someone else built it?'),
      ('skills-canada-157', 'Watching the upper limit of any trade helps you understand what mastery actually looks like. As you think about what you want to be good at, who would you watch for hours to figure out where the bar is set?'),
      ('skills-canada-158', 'Most trades reward people who are useful in small ways consistently, not impressive occasionally. As you think about your own work style, are you patient enough to be quietly reliable for years, even when the impressive role is years away?')
  )
  update public.content c
  set reflection = v.new_reflection
  from v
  where c.id = v.id;

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
