-- Refresh description and takeaway for the 68 non-Skills-Canada videos.
-- Generated by scripts/generate-non-skills-copy-migration.py from scripts/data/copy-updates/non-skills-video-copy-update.json.
-- Targets rows by stable slug; excludes Skills Canada rows defensively.
-- Fails the transaction if the expected number of rows is not updated.

do $$
declare
  expected_count int := 68;
  actual_count int;
begin
  with v(slug, new_description, new_takeaway) as (values
      ('sunshine-breaks-at-work', 'A comedic argument that non-smokers should get sunshine breaks at work, the same way smokers step outside.', 'Workplace norms aren''t fixed — the perks people take for granted often started as someone speaking up.'),
      ('how-to-get-higher-salary', 'A quick rundown of how to negotiate salary once you have an offer in hand.', 'The moment between offer and acceptance is the highest leverage you''ll ever have — don''t skip the ask.'),
      ('responding-to-inappropriate-interview-questions', 'How to redirect interview questions that veer into personal or off-limits territory without burning the bridge.', 'You can decline a question and stay in the running — knowing what''s off-limits is part of professional fluency.'),
      ('watch-out-for-ai-scams', 'A warning about AI-powered fake recruiters and job offers, and the red flags that give them away.', 'Job hunting now means screening employers for legitimacy as carefully as they screen you.'),
      ('financial-independence-for-partners', 'Why partners who don''t earn an income still need their own money, accounts, and credit history.', 'Career and financial independence aren''t only about a paycheque — they''re about options if circumstances change.'),
      ('hidden-value-of-service-jobs', 'The transferable skills hiring managers actually look for in retail, food, and customer-facing work.', 'Your first job is rarely about the work itself — it''s about proving you can handle pressure, people, and routine.'),
      ('power-of-compound-interest', 'A short fable that shows what happens when you start investing small amounts early versus large amounts later.', 'Time, not income, is the biggest lever in long-term saving — starting at 18 beats starting at 28 with double the money.'),
      ('unlimited-pto-red-flag', 'How to read between the lines on "unlimited vacation" policies and tell whether you''d actually use them.', 'Benefits only matter if you can actually take them — culture decides whether a perk is real.'),
      ('what-not-to-say-job-offer', 'The one phrase that signals "I''ll take whatever you give me" and shuts down any chance to negotiate.', 'How you respond to an offer in the first 60 seconds sets the tone for your entire compensation.'),
      ('always-accept-a-raise', 'Debunking the myth that earning more money puts you in a tax bracket that costs you take-home pay.', 'Marginal tax brackets only apply to the new money — accepting a raise always leaves you better off.'),
      ('star-method-interviews', 'A walkthrough of the Situation-Task-Action-Result framework for answering "tell me about a time..." questions.', 'Structured stories beat vague claims — the same examples can be reused across most behavioural interview questions.'),
      ('avoiding-workplace-drama', 'How to recognize coworkers who feed on conflict, and the boundaries that keep you out of it.', 'Staying neutral early in your career protects your reputation — gossip travels faster than results.'),
      ('dream-job-after-accepting-another', 'What to do when your dream offer lands days after you''ve already signed somewhere else.', 'Reneging on an accepted offer is rare but sometimes the right call — knowing how to do it professionally matters.'),
      ('setting-boundaries-people-pleaser', 'Practical scripts for saying no at work when your default is to say yes.', 'Boundaries aren''t rude — they''re how high performers protect the time they need to do their actual job well.'),
      ('discussing-salary-with-coworkers', 'Your legal right to discuss pay with colleagues, and why companies often discourage it anyway.', 'Pay transparency between coworkers is one of the fastest ways to find out if you''re being underpaid.'),
      ('how-to-brag-at-work', 'How to talk about your wins so they get noticed without sounding like you''re showing off.', 'If your manager doesn''t know what you did, it didn''t happen — self-promotion is a learnable skill.'),
      ('why-do-you-want-to-work-here', 'A reframing trick for the "why this company?" question that avoids sounding rehearsed.', 'Specific beats enthusiastic — naming something concrete proves you actually did the research.'),
      ('subtle-art-of-small-talk', 'How to handle small talk with coworkers, clients, and interviewers when it doesn''t come naturally.', 'Small talk isn''t filler — it''s how trust gets built before the real conversation starts.'),
      ('impossible-interview-questions', 'How to handle interview questions designed to throw you off, like "what''s your biggest weakness?"', 'Trick questions usually test composure, not knowledge — buy yourself a beat to think before answering.'),
      ('psychological-trick-winning-arguments', 'A communication technique that defuses workplace disagreements by acknowledging the other side first.', 'Most workplace arguments aren''t won on logic — they''re won by making the other person feel heard.'),
      ('recovering-from-toxic-boss', 'What to expect — and what it feels like — after leaving a manager who was undermining you.', 'Toxic workplaces leave scars that show up in your next job; recognizing them is the first step to not carrying them along.'),
      ('secret-interview-etiquette-tips', 'Small interview habits — eye contact, follow-up emails, post-interview silence — that most people miss.', 'Candidates who get offers don''t just answer well; they handle the etiquette around the conversation too.'),
      ('why-promotions-arent-always-good', 'When a promotion is actually a trap — more responsibility, marginally more pay, and work you''ll dislike.', 'Career growth isn''t always vertical — sometimes the smarter move is to stay where you are or step sideways.'),
      ('beware-remote-job-scams', 'The most common ways scammers target remote job seekers, and the red flags to spot them quickly.', 'If a remote job offer feels too easy — no real interview, no background check, payment up front — it usually is.'),
      ('salary-negotiation-not-personal', 'A reminder that asking for more money is a normal business conversation, not a confrontation.', 'Employers expect you to negotiate — not asking can leave thousands of dollars on the table over a career.'),
      ('celebrities-pay-120k-for-it', 'An interview with someone who provides a high-end service that A-list celebrities pay six figures for.', 'The most lucrative careers often don''t have job titles you''d recognize from a school career fair.'),
      ('making-millions-at-12', 'A young entrepreneur talks about building a profitable business before becoming a teenager.', 'Career experience can start before you can legally drive — opportunity scales with curiosity, not age.'),
      ('legendary-mum-crazy-gift', 'A career-ladder interview with a Singaporean mother whose unusual talent became her livelihood.', 'Some careers grow out of a hobby or natural ability — niche skills can quietly turn into a living.'),
      ('15-year-old-genius', 'A teenage prodigy talks about how his early talents are already shaping his career path.', 'A clear interest at 15 doesn''t have to wait until graduation — there are real ways to start building on it now.'),
      ('only-3-people-do-her-job', 'A career-ladder interview with someone holding one of just three positions like it on Earth.', 'Some careers are so specialized they don''t appear in any database — you find them by following curiosity, not job boards.'),
      ('artificially-gives-better-body', 'An interview with a professional who reshapes bodies through cosmetic and aesthetic techniques.', 'Whole industries exist around appearance and aesthetics, with career paths ranging from technician to artist.'),
      ('kings-queens-paddington-bear', 'A career-ladder interview with someone whose job sits at the intersection of British royalty and pop culture.', 'Jobs that touch tradition, culture, and the arts often hide in plain sight — and rarely advertise themselves.'),
      ('kids-love-her-hot-job', 'A career-ladder interview with a professional whose work delights kids and involves serious heat.', 'Some of the most fulfilling careers are the ones you discover by watching what kids actually get excited about.'),
      ('what-i-mean-by-famous', 'An interview with someone famous within their industry but invisible to the general public.', 'Most "famous" people aren''t household names — they''re the best in a niche, and those niches are everywhere.'),
      ('first-responder-edition', 'A career-ladder interview with a first responder about what the role actually demands day-to-day.', 'Emergency services careers are physical, mental, and emotional all at once — the training is built around that.'),
      ('back-with-side-job', 'A returning guest explains how she runs a side hustle alongside her main career.', 'Side jobs aren''t just for money — they''re how people test new directions without quitting their day job.'),
      ('job-analogous-to-mirrors', 'An interview with someone whose unusual job involves reflecting and reshaping how people see themselves.', 'Some jobs are about transformation — making the person you serve look or feel different than when they arrived.'),
      ('first-woman-to-do-job-twice', 'A trailblazer talks about being the first woman to hold a specific role — twice over.', 'Breaking into a field is one challenge; staying long enough to do it again is a different one entirely.'),
      ('nominated-by-whole-school', 'A student whose entire school nominated him for a recognition that opened career doors.', 'Peer recognition often opens doors that grades alone can''t — being known for something specific matters.'),
      ('wont-guess-in-million-years', 'A career-ladder interview that challenges you to guess this Australian''s unexpected line of work.', 'The world is full of careers you''ve never heard of — staying curious is most of the work.'),
      ('job-needs-patience', 'An interview about a career in Brazil that takes years of patience to do well — and longer to master.', 'Careers built on patience and craft rarely look impressive day-to-day, but they compound into something rare.'),
      ('trains-bosses-manage-gen-z', 'A consultant who teaches managers how to lead Gen Z employees without losing them.', 'Workplace generational gaps are big enough that there''s a whole career in translating between them.'),
      ('dream-job-pays-well', 'An interview with someone whose career combines genuine passion with strong compensation.', '"Do what you love" and "make good money" aren''t mutually exclusive — they''re a third category most people don''t search for.'),
      ('discovered-new-fire-creature', 'Scientists have found an organism that survives in extreme heat — and what its biology might mean for medicine and materials.', 'Biologists who study extreme environments are reshaping fields from drug discovery to materials science.'),
      ('quantum-gps-device', 'A look at a quantum-based navigation device that works where regular GPS can''t — and the engineering behind it.', 'Quantum technology is moving out of physics labs and into commercial products — engineers who can bridge both are in demand.'),
      ('shoes-alter-your-brain', 'How sensory-feedback footwear is being designed to influence balance, gait, and brain activity.', 'Neuroscience, biomechanics, and product design are converging — and new careers are forming in the overlap.'),
      ('what-is-3i-atlas-made-of', 'Astronomers break down the composition of 3I/ATLAS, the third confirmed interstellar object ever spotted.', 'Astrochemistry — figuring out what space objects are made of from light alone — is a small field with outsized impact.'),
      ('medical-treatment-saved-boy', 'How a recent gene therapy gave a child with a rare condition a new outcome.', 'Personalized medicine careers — from lab tech to genetic counsellor — are growing as one-off cures become real.'),
      ('white-leds-almost-didnt-exist', 'The decades-long research story behind white LEDs, the technology that lights most modern screens and rooms.', 'Breakthroughs in materials science often take 20+ years and quiet careers — most of the world never learns who did the work.'),
      ('massive-machine-under-antarctica', 'A tour of the enormous scientific instrument buried beneath the Antarctic ice — and what it''s listening for.', 'Antarctic science careers blend physics, engineering, and extreme logistics — people who can do all three are rare.'),
      ('smallest-black-hole', 'What scientists know about the lower size limit of black holes, and what finding a tiny one would teach us.', 'Theoretical astrophysicists work on questions where the answer might not arrive in their career — patience is part of the job.'),
      ('sahara-fertilizes-amazon', 'How nutrient-rich dust from the Sahara is carried across the Atlantic and keeps the Amazon alive.', 'Climate science careers depend on connecting systems that look unrelated — atmosphere, oceans, ecosystems, all one problem.'),
      ('snowflakes-have-6-sides', 'The molecular reason every snowflake forms six points, and what it reveals about crystal growth.', 'Crystallography sits behind drug development, semiconductors, and materials science — small structures, huge careers.'),
      ('prehistoric-animal-survived', 'A test of which ancient species made it through the mass extinction that ended the dinosaurs.', 'Paleontology careers aren''t just digging fossils — they''re piecing together survival rules that apply to today''s climate.'),
      ('plane-needs-3-pilots', 'The aircraft category where three pilots are still required, and the engineering decisions that demand it.', 'Aerospace careers blend hardware, regulations, and human factors — even who sits in the cockpit is engineered.'),
      ('scientists-bullied-octopus', 'The experimental design behind a study that revealed how cephalopods remember and react to specific people.', 'Animal cognition research is reshaping how we define intelligence — and the careers studying it are growing fast.'),
      ('biggest-planet-ever-found', 'A tour of the largest known exoplanet and what its size says about how planets form.', 'Exoplanet discovery is now a routine career path — twenty years ago, we knew of zero.'),
      ('deep-sea-creature-first-time', 'The first-ever footage of a deep ocean animal that scientists had only theorized existed.', 'Marine biology careers are still discovering new species every year — the deep ocean is less mapped than the moon.'),
      ('airplane-fuel-floating', 'A look at why some jet fuel can separate or float in tanks, and what aviation engineers do about it.', 'Fuel chemistry is a quiet but career-defining field — small molecular issues can become global safety problems.'),
      ('fly-through-asteroid-belt', 'What movies get wrong about the asteroid belt, and what spacecraft actually face when crossing it.', 'Mission planning and orbital mechanics are careers where the math has to be right the first time, every time.'),
      ('dinosaur-mummies-are-real', 'How exceptionally preserved dinosaur remains — soft tissue and all — change what we know about prehistoric life.', 'Paleontology is becoming a chemistry and imaging field as much as a digging one — interdisciplinary careers welcome.'),
      ('how-many-humans-ever-lived', 'How demographers estimate the total number of humans that have ever walked the Earth, and why the number is hard to pin down.', 'Demography sits behind public health, economics, and climate policy — careers in counting people shape big decisions.'),
      ('plane-cured-fear-of-flying', 'How a recent aircraft''s design choices reduce turbulence and the cues that trigger anxiety mid-flight.', 'Human factors engineering — designing for how people actually feel — is a growing field across transportation.'),
      ('stop-dangerous-asteroid', 'The technologies being developed to deflect an asteroid headed for Earth — and how recent missions tested them.', 'Planetary defence is a real career path now, not a movie plot — and the playbook is being written by the engineers who choose it.'),
      ('microrobot-save-your-life', 'Microscopic robots designed to travel through the body and deliver targeted treatments.', 'Microrobotics blends mechanical engineering, biology, and AI — early-career researchers are defining what''s possible.'),
      ('something-alive-earths-crust', 'The discovery of organisms living kilometres underground, and what their biology suggests about life elsewhere.', 'Astrobiologists study Earth''s extremes to understand what life on other planets might look like — careers built on the question are growing.'),
      ('whats-up-with-atlas-tail', 'The unexpected behaviour of 3I/ATLAS''s tail and what astronomers think it reveals about its origin.', 'Comet and small-body scientists chase rare events — when an interstellar object passes through, their whole career bends around it.'),
      ('experiment-saved-kids-lives', 'The clinical trial whose results led directly to a treatment now saving children with a previously fatal disease.', 'Clinical research careers turn one experiment into measurable outcomes for patients — slow work, enormous impact.')
  )
  update public.content c
  set description = v.new_description,
      takeaway    = v.new_takeaway
  from v
  where c.slug = v.slug
    and c.content_type = 'video'
    and c.id not like 'skills-canada-%';

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
