-- Refresh takeaway for the 8 mindsets Skills Canada videos.
-- Generated by scripts/generate-skills-canada-copy.py from scripts/data/copy-updates/skills-canada-mindsets-copy-update.json.
-- Targets rows by stable id; descriptions are intentionally left untouched.
-- Fails the transaction if the expected number of rows is not updated.

do $$
declare
  expected_count int := 8;
  actual_count int;
begin
  with v(id, new_takeaway) as (values
      ('skills-canada-035', 'What a career pays in year one and what it pays in year five are different worlds — especially in trades, the starting wage hides the actual trajectory.'),
      ('skills-canada-067', 'The founder advice that compounds is the kind that names what won''t change about your customers in 10 years — tactics rotate, underlying needs don''t.'),
      ('skills-canada-078', 'The shift that turns a presentation around is moving from "don''t mess up" to "make one idea land" — most polished talks fail because they aim at the wrong target.'),
      ('skills-canada-079', 'Industrial mechanics rewards people who like systems thinking and physical work in equal parts — the trait to look for is curiosity about how things break.'),
      ('skills-canada-096', 'Trades careers don''t change to fit you — but they''re more open than reputations suggest, and finding one person inside who''ll answer questions changes the path entirely.'),
      ('skills-canada-099', 'What''s drawing Gen Z into electrical work isn''t pay alone — it''s the rare combination of debt-free training, certified skill, and work that can''t move overseas.'),
      ('skills-canada-100', 'Great electricians don''t just know code — they read the room, anticipate the next problem, and treat speed and safety as the same skill, not opposites.'),
      ('skills-canada-109', 'Industrial mechanics rewards people who like systems thinking and physical work in equal parts — the trait to look for is curiosity about how things break.')
  )
  update public.content c
  set takeaway = v.new_takeaway
  from v
  where c.id = v.id
    and c.content_type = 'video'
    and c.id like 'skills-canada-%';

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
