-- Refresh takeaway for the 13 job-board Skills Canada videos.
-- Generated by scripts/generate-skills-canada-copy.py from scripts/data/copy-updates/skills-canada-job-board-copy-update.json.
-- Targets rows by stable id; descriptions are intentionally left untouched.
-- Fails the transaction if the expected number of rows is not updated.

do $$
declare
  expected_count int := 13;
  actual_count int;
begin
  with v(id, new_takeaway) as (values
      ('skills-canada-094', 'Skilled trades reward people who like seeing the end product of their day — if you''d rather walk past something you built than scroll past something you posted, this path fits.'),
      ('skills-canada-095', 'Trades pay scales with certification, overtime, and location — the $100k headlines are real, but they belong to people who chase the right ticket, not just the right job.'),
      ('skills-canada-110', 'Industrial mechanic work happens where everything else stops working — if you like the puzzle of an unfamiliar broken machine more than a tidy office routine, this fits.'),
      ('skills-canada-112', 'Mechatronics sits at the intersection of mechanical, electrical, and software — pick it if you want to work on machines that move, sense, and decide, not just one of the three.'),
      ('skills-canada-123', 'Aerospace engineering rewards exactness over speed — the careers go to people who care about being right, not first, and don''t mind that the work takes years to ship.'),
      ('skills-canada-126', 'Automotive tech is shifting from mechanical work to software and high-voltage systems — the careers belong to people who''ll keep learning new platforms every few years.'),
      ('skills-canada-135', '"Best careers" lists rotate every year — the durable signal underneath them is which trades and tech roles are short on workers, so chase shortages, not buzz.'),
      ('skills-canada-139', 'Graphic design jobs aren''t just artists — they''re problem-solvers with a visual vocabulary, working with marketing, product, and clients on a brief most days.'),
      ('skills-canada-141', 'Animation is a long pipeline of small decisions — most of the job is iterating on someone else''s idea, not invention; pick it if you find satisfaction in the iteration itself.'),
      ('skills-canada-145', 'Engineering technologists do the practical translation between designs and what actually gets built — the role suits people who like both math and a multimeter.'),
      ('skills-canada-147', 'Web development is one of the lowest-friction careers to start — a laptop and a few months of self-teaching can make you productive before any degree.'),
      ('skills-canada-152', 'Mechanical engineering is broad enough that no two roles look alike — pick it for the optionality, not because you''ve already decided on one specific kind of work.'),
      ('skills-canada-155', 'Cabinetmaking pays the people who can read a customer''s vague brief and turn it into a buildable plan — half the craft is the conversation before the cut.')
  )
  update public.content c
  set takeaway = v.new_takeaway
  from v
  where c.id = v.id
    and c.content_type = 'video'
    and c.id like 'skills-canada-%';

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
