-- Backfill reflection for the 8 'skills-canada-life-skills' rows.
-- Generated by scripts/generate-reflections-migration.py from scripts/data/reflections/skills-canada-life-skills.json.
-- Targets rows by stable id. Fails the transaction if the expected row
-- count is not updated.

do $$
declare
  expected_count int := 8;
  actual_count int;
begin
  with v(id, new_reflection) as (values
      ('skills-canada-040', 'Most career conversations in high school focus on what comes after, but some paths begin in the classroom itself. As you think about your own next move, would it change anything to know you could be earning and learning a trade before you graduate?'),
      ('skills-canada-058', 'Some of the steadiest careers are ones most people have never heard of. As you think about your future, how would you actually go about finding a path that pays well but does not get talked about, and who would you ask?'),
      ('skills-canada-101', 'We tend to compare debt and salary as if they are the same kind of number. As you think about your own path after high school, what would it mean to start your working life debt-free and earning sooner, even if the title sounds different than university?'),
      ('skills-canada-118', 'Most students think engaging speakers are simply louder or more confident. As you think about your own voice in front of a group, what is one small thing you could change about how you speak that you have never tried on purpose?'),
      ('skills-canada-119', 'There is a quiet myth that confidence requires extroversion. As you think about how you show up in front of others, what kind of preparation or small ritual would let you sound like yourself, only steadier?'),
      ('skills-canada-120', 'Most fears shrink with exposure, not with effort to feel less afraid. As you think about something that scares you about your future, is there a small, low-stakes version of it you could practice this month before it gets bigger?'),
      ('skills-canada-159', 'Pauses feel longer to the speaker than to the audience. As you think about how you talk in front of others, what would it change to treat the silences between your words as part of what you are saying?'),
      ('skills-canada-160', 'Some skills only get better through doing them in front of real people. As you think about something you want to be good at after high school, how could you find small, real audiences for it before the stakes get high?')
  )
  update public.content c
  set reflection = v.new_reflection
  from v
  where c.id = v.id;

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
