-- Backfill reflection for the 25 'skills-canada-how-i-got-here' rows.
-- Generated by scripts/generate-reflections-migration.py from scripts/data/reflections/skills-canada-how-i-got-here.json.
-- Targets rows by stable id. Fails the transaction if the expected row
-- count is not updated.

do $$
declare
  expected_count int := 25;
  actual_count int;
begin
  with v(id, new_reflection) as (values
      ('skills-canada-001', 'The headline number is one snapshot. As you think about your own path after high school, what matters more to you: the average pay, the ceiling, or how quickly you start earning?'),
      ('skills-canada-013', 'Finishing something real teaches what finishing a test never will. As you think about how you actually learn best, are you the kind of person who needs the project to fail at least once before you understand it?'),
      ('skills-canada-014', 'Some roles you get to in your thirties, not your twenties. As you think about a career you might want eventually, would you be willing to spend a decade in adjacent jobs first, picking up the pieces of what the eventual role really needs?'),
      ('skills-canada-016', 'Shipping something small almost always teaches more than aiming bigger and never finishing. As you think about a creative project of your own, what is the smallest version of it you could actually release this year?'),
      ('skills-canada-020', 'Some jobs make something that disappears by lunch. As you think about your own preferences, would you find satisfaction in repeating the work itself every day, or do you need something that adds up into a finished product you can point to?'),
      ('skills-canada-023', 'Most creative businesses run on the parts people did not realize they had to learn. As you think about a thing you would love to do for money, what would you have to get good at that has nothing to do with the craft itself?'),
      ('skills-canada-025', 'In many creative fields, average pay hides a wide split between most workers and a small specialized group. As you think about a career you are drawn to, what would it take to be in that specialized group instead of the general one?'),
      ('skills-canada-027', 'Most service businesses get hired for judgment, not gear. As you think about something you might one day sell, what would your point of view be, and how would someone know it from one minute with you or your work?'),
      ('skills-canada-036', 'Some professions still let you skip the credential if you can do the work. As you think about a field you are drawn to, does the traditional path matter to you because of the skills it teaches, or because of the certainty it provides?'),
      ('skills-canada-042', 'Many trades careers grow through a quiet shift from doing the work to also running the work. As you imagine your future, do you want to stay on the tools long-term, or eventually run a small shop with other people doing the cutting?'),
      ('skills-canada-055', 'Some careers ask you to be useful in multiple trades at once. As you think about your own way of learning, are you the kind of person who likes going deep into one area, or would it suit you to be the bridge between several?'),
      ('skills-canada-061', 'Some trades stay in demand because the work cannot move overseas. As you think about your own career security, would it matter to you that your craft has to be done physically, on site, by someone with the right ticket?'),
      ('skills-canada-062', 'Some careers show up at the worst moments and feel like a rescue. As you imagine your own work, would you rather be the person fixing something that is broken right now, or the one quietly preventing breakdowns no one notices?'),
      ('skills-canada-072', 'Most jobs talk about salary as if it is the same year one and year ten. As you think about your own future earnings, what kinds of questions would you ask a person already in a career to find out what the trajectory actually looks like?'),
      ('skills-canada-076', 'Big single-day revenue numbers usually come from a specific kind of work most people in the trade do not chase. As you think about a career you might enter, where would you have to specialize to be paid like the high end, not the average?'),
      ('skills-canada-091', 'Most successful founders started with something small and unimpressive. As you think about your own first attempt at anything ambitious, what would it take to lower the bar enough to actually start, instead of waiting for a bigger idea?'),
      ('skills-canada-097', 'Trying things is faster than thinking your way into the right one. As you think about your next year of high school, what is one thing you are curious about that you could test in a small, low-cost way before committing?'),
      ('skills-canada-098', 'Career advice that worked for one person rarely fits exactly for another. As you take in advice from people around you, what would it change to listen for how they made decisions instead of trying to copy what they decided?'),
      ('skills-canada-105', 'Most people end up doing work that was not on their radar at 18. As you think about your own next step, does that feel like a reason to pick something flexible, or a reason to commit hard and trust that you will change later anyway?'),
      ('skills-canada-106', 'Some paths begin years before graduation if you know to ask. As you think about your own remaining time in high school, would you trade some of it for the chance to start earning in a trade before you walk the stage?'),
      ('skills-canada-116', 'Some careers sit halfway between trades and tech. As you think about your own preferences, do you want a clean split between hands-on work and screen work, or would you welcome a job that asks you to switch between them all day?'),
      ('skills-canada-121', 'Many tech careers start with something you built at home that gives you a story to tell. As you think about a field you might enter, what is one small thing you could make this month that would prove you can do the work?'),
      ('skills-canada-122', 'In many tech careers, generalist pay is okay and specialist pay jumps. As you think about your own next few years, would you focus on broad competence first and specialize later, or pick a niche early and grow in depth?'),
      ('skills-canada-142', 'Studios mostly hire from a small group of people who keep showing them new work. As you think about a field you are drawn to, how would you go about being one of the people who stays visible to the gatekeepers over time?'),
      ('skills-canada-149', 'Some professional careers really do open in months, not years. As you think about your own appetite for self-teaching, does the speed sound exciting or risky, and what would you need to keep yourself accountable through it?')
  )
  update public.content c
  set reflection = v.new_reflection
  from v
  where c.id = v.id;

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
