-- Refresh takeaway for the 14 post-secondary Skills Canada videos.
-- Generated by scripts/generate-skills-canada-copy.py from scripts/data/copy-updates/skills-canada-post-secondary-copy-update.json.
-- Targets rows by stable id; descriptions are intentionally left untouched.
-- Fails the transaction if the expected number of rows is not updated.

do $$
declare
  expected_count int := 14;
  actual_count int;
begin
  with v(id, new_takeaway) as (values
      ('skills-canada-003', 'Carpentry certificates open the door to apprenticeship-eligible work — the credential isn''t the finish line, it''s the ticket to the much longer paid-learning path that follows.'),
      ('skills-canada-010', 'Apprenticeship grants quietly remove the biggest barrier to trades training — the cost of unpaid first months — and the policies around them change fast enough to be worth checking before you commit.'),
      ('skills-canada-017', 'Creative-program portfolios are judged on point of view, not polish — admissions committees spot generic work fast, but a small body of consistent personal projects beats a glossy showpiece.'),
      ('skills-canada-045', 'Plumbing programs at colleges like Sheridan are usually the first half of a longer apprenticeship — graduating gets you working, not certified, and the rest happens on real job sites.'),
      ('skills-canada-051', 'Welding training is short enough to fit between jobs and credentialed in tiers — you can start working as a fitter or general welder and stack certifications as your skill grows.'),
      ('skills-canada-053', 'Architectural technology programs prepare you for the production side of design — making the drawings builders actually use — which is a faster path into the industry than an architecture degree.'),
      ('skills-canada-074', 'Cosmetology school is more clinic than classroom — most of what you take into the chair comes from real client hours, not lectures, so pick a program by its practical setup.'),
      ('skills-canada-124', 'Engineering degrees pay back differently depending on the field — aerospace rewards patience and depth, so it''s worth it for people who already love the long arc, not the quick cycle.'),
      ('skills-canada-127', 'Automotive engineering programs now spend as much time on software and electric drivetrains as on combustion — choose a school whose curriculum reflects where the industry is going, not where it''s been.'),
      ('skills-canada-130', 'Heavy-duty mechanic training pays off because the machines don''t move to where the workers are — graduates with the right tickets travel to wherever industry needs them, and the pay reflects it.'),
      ('skills-canada-137', 'Fulfilling careers usually aren''t picked from a list — they show up at the intersection of what you''ll do for free and what someone will pay for, and noticing that overlap takes time.'),
      ('skills-canada-144', 'Electronics technician training is mostly hands-on with real components — pick a program with a strong lab so you graduate able to diagnose, not just describe.'),
      ('skills-canada-150', 'Engineering school is closer to a job than a university experience for most — the volume of work is real, and the people who thrive treat it like training for a profession, not picking a major.'),
      ('skills-canada-156', 'Furniture-making programs train you for both production work and starting your own shop — the path forks early between volume cabinetry and one-off pieces, and the program choice should match the path.')
  )
  update public.content c
  set takeaway = v.new_takeaway
  from v
  where c.id = v.id
    and c.content_type = 'video'
    and c.id like 'skills-canada-%';

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
