-- Refresh takeaway for the 27 emerging-careers Skills Canada videos.
-- Generated by scripts/generate-skills-canada-copy.py from scripts/data/copy-updates/skills-canada-emerging-careers-copy-update.json.
-- Targets rows by stable id; descriptions are intentionally left untouched.
-- Fails the transaction if the expected number of rows is not updated.

do $$
declare
  expected_count int := 27;
  actual_count int;
begin
  with v(id, new_takeaway) as (values
      ('skills-canada-002', 'Apprenticeship works best when you can shadow people one or two stages ahead of you. Mentorship inside a trade is what turns a four-year program into a career.'),
      ('skills-canada-006', 'Hairstyling apprenticeships pay while you learn the technical side of the trade in real salons. The model means you can be earning by 19 and running your own chair by 23 if you take it seriously.'),
      ('skills-canada-007', 'Trades training in Canada is being modernized to match what shops actually need now: more apprentices, faster certification, more pathways from high school. The policy backdrop is moving in favour of the people entering.'),
      ('skills-canada-008', 'The Red Seal certification makes a Canadian electrician''s qualifications portable across every province. Finishing it usually takes about four years and opens up the higher-paying industrial work.'),
      ('skills-canada-009', 'Some careers click early because the work is visible: you can see whether you like it before you commit. Hairstyling is one of the trades where a few hours observing in a salon tells you most of what the next decade will feel like.'),
      ('skills-canada-028', 'CNC machining is one of the cleanest tech-meets-trade jobs around. The work is half programming, half setup, with the satisfaction of producing parts that other manufacturers depend on.'),
      ('skills-canada-033', 'Software careers branch sideways more than they climb. The pivots that pay well usually involve specializing in infrastructure that other engineers depend on, like cloud or data systems.'),
      ('skills-canada-039', 'Medical esthetics is a fast-growing field that sits between cosmetics and healthcare. It rewards people willing to keep up with new procedures and the regulatory side that comes with working closer to medicine.'),
      ('skills-canada-041', 'Cabinetmaker careers compound when you start specializing. Generalists make a living; specialists in commercial casework, furniture, or restoration make several times that.'),
      ('skills-canada-046', 'Sheet metal work spans HVAC, roofing, custom architectural pieces, and aerospace. The trade ages well because every category needs the same fabrication skills but pays in very different bands.'),
      ('skills-canada-050', 'Steamfitters work where pressure systems matter, which includes hospitals, refineries, and ships. The certification is harder to get than most plumbing trades and the work pays accordingly.'),
      ('skills-canada-056', 'Masonry pays apprentices on real job sites from day one, and finished work lasts a century. It''s one of the few trades where the longevity of what you build matches the length of the career it gives you.'),
      ('skills-canada-065', 'One-person video production businesses succeed when they pick one client type and serve it well, not when they try to do everything. The trap is buying gear faster than you build a niche.'),
      ('skills-canada-066', 'Graphic design pay is shifting toward people who can also write copy, motion-design, or strategize, not just produce visuals. Pure designers still work, but the highest earners layer skills.'),
      ('skills-canada-069', 'Stick welding pays a premium because the conditions are usually hard: outdoors, structural, often at heights. Welders who can run a stick rod cleanly stay in demand even as automation grows elsewhere.'),
      ('skills-canada-073', 'Landscaping businesses scale by stacking simple, repeatable services for the same clients season after season. The path to $20K months runs through retention, not novelty.'),
      ('skills-canada-081', 'Fashion as an industry rewards people who can both design and explain why something works for a target customer. Learning the business side early is what separates working designers from hobbyists.'),
      ('skills-canada-082', 'Auto body specialists at the top of the trade earn what mid-career engineers do, because their work is harder to outsource and easier to charge by the job. The route is owning your shop or specializing in collision insurance work.'),
      ('skills-canada-083', 'The highest-paying trades cluster around heavy industry, mining, and oil and gas. The pay reflects location, hazard, and shift work, not just skill — pick based on the trade-offs you''ll actually live with.'),
      ('skills-canada-084', 'Trade salaries surprise people in both directions: some quiet trades pay much more than expected, and some glamorous ones less. Hourly wage is only part of the picture; benefits, overtime, and seasonal patterns matter at least as much.'),
      ('skills-canada-087', 'An electrician''s career has three obvious stages: apprentice, journeyman, master. The less-obvious one is the optional fourth: starting your own shop, where the pay scales differently than it does on the tools.'),
      ('skills-canada-088', 'Plumber pay scales especially fast for people willing to work on industrial systems or own their own service business. Residential service work is the entry point, not the destination.'),
      ('skills-canada-089', 'Hairstyling days look short on paper but include early prep, slow client weeks, and a lot of standing. The career suits people who can stay energetic with strangers for hours and treat each chair as a small project.'),
      ('skills-canada-107', 'Auto body shops are integrating AI for damage estimation and parts ordering, but the hands-on repair work is still hard to automate. Technicians who can use these tools well are likely to come out ahead, not be replaced by them.'),
      ('skills-canada-113', 'Mechatronics roles span manufacturing automation, robotics, and renewable energy installation. The common thread is systems that combine mechanical motion with sensors and code, and these systems are showing up in more industries every year.'),
      ('skills-canada-114', 'Mechatronics engineering blends mechanical, electrical, and software engineering into one discipline. Picking it is a bet that the next generation of products will keep crossing those boundaries, which most of them already do.'),
      ('skills-canada-117', 'Machinists make the parts other industries depend on, often working from blueprints to tolerances measured in thousandths. The career ages well because the underlying skills transfer across aerospace, medical devices, and custom industrial work.')
  )
  update public.content c
  set takeaway = v.new_takeaway
  from v
  where c.id = v.id
    and c.content_type = 'video'
    and c.id like 'skills-canada-%';

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
