-- Seed long-term care playlist videos.
-- Source playlist: https://www.youtube.com/playlist?list=PLLtApeuxxAfOTLtLRfCUtRADz65j-49Qa
-- Generated by scripts/generate-long-term-care-migration.py from scripts/data/long-term-care-videos.json.

do $$
declare
  expected_count int := 17;
  actual_count int;
  linked_count int;
begin
  if not exists (select 1 from public.categories where slug = 'on-the-job') then
    raise exception 'Missing required category: on-the-job';
  end if;

  insert into public.content (
    id,
    slug,
    title,
    description,
    content_type,
    thumbnail_url,
    video_url,
    video_orientation,
    video_duration,
    published_at,
    is_published,
    takeaway
  )
  values
    ('ltc-careers-001', 'food-service-worker-career-long-term-care', 'Food Service Worker: A Career in Long-Term Care', 'Meet a food service worker in long-term care and see how meal prep, resident relationships, and reliable routines shape the workday.', 'video', 'https://img.youtube.com/vi/7G-UpESNmnU/maxresdefault.jpg', 'https://www.youtube.com/watch?v=7G-UpESNmnU', 'horizontal', 141, now() - (1 * interval '1 second'), true, 'Support roles in health care are not only clinical; food service workers help turn care plans into daily comfort.'),
    ('ltc-careers-002', 'nursing-career-long-term-care', 'Nursing: A Career in Long-Term Care', 'A look at nursing in long-term care, from clinical judgement and medication support to the relationships nurses build with residents.', 'video', 'https://img.youtube.com/vi/tQ76a76jHjA/maxresdefault.jpg', 'https://www.youtube.com/watch?v=tQ76a76jHjA', 'horizontal', 121, now() - (2 * interval '1 second'), true, 'Long-term care nursing rewards people who want clinical skill and sustained human connection in the same career.'),
    ('ltc-careers-003', 'recreation-professional-career-long-term-care', 'Recreation Professional: A Career in Long-Term Care', 'Follow a recreation professional who plans activities, creates social moments, and helps residents stay connected to interests and community.', 'video', 'https://img.youtube.com/vi/aQYjuPzqhns/maxresdefault.jpg', 'https://www.youtube.com/watch?v=aQYjuPzqhns', 'horizontal', 187, now() - (3 * interval '1 second'), true, 'Recreation work shows how creativity and care can belong in the same health-care career path.'),
    ('ltc-careers-004', 'food-services-careers-long-term-care', 'Food Services: Careers in Long-Term Care', 'Explore the broader food services team in long-term care and how kitchen work, nutrition needs, and resident preferences come together.', 'video', 'https://img.youtube.com/vi/hZ3u_4Bswpc/hqdefault.jpg', 'https://www.youtube.com/watch?v=hZ3u_4Bswpc', 'horizontal', 274, now() - (4 * interval '1 second'), true, 'Behind every meal is a team balancing safety, dignity, culture, and care for people they see every day.'),
    ('ltc-careers-005', 'physiotherapy-career-long-term-care', 'Physiotherapy: A Career in Long-Term Care', 'See how physiotherapy supports mobility, confidence, recovery, and independence for residents in a long-term care setting.', 'video', 'https://img.youtube.com/vi/g2zIy3NHh-0/maxresdefault.jpg', 'https://www.youtube.com/watch?v=g2zIy3NHh-0', 'horizontal', 229, now() - (5 * interval '1 second'), true, 'Physiotherapy in long-term care is about helping people keep as much independence as possible, one practical movement at a time.'),
    ('ltc-careers-006', 'housekeeping-career-long-term-care', 'Housekeeping: A Career in Long-Term Care', 'A day-in-the-work look at housekeeping in long-term care, where cleanliness, safety, and resident respect are part of the same job.', 'video', 'https://img.youtube.com/vi/Y6g7-XDNqpQ/maxresdefault.jpg', 'https://www.youtube.com/watch?v=Y6g7-XDNqpQ', 'horizontal', 162, now() - (6 * interval '1 second'), true, 'Housekeeping is frontline care too; clean, safe spaces change how residents feel and how the whole home runs.'),
    ('ltc-careers-007', 'social-work-career-long-term-care', 'Social Work: A Career in Long-Term Care', 'Meet social work in long-term care and how the role supports residents, families, transitions, advocacy, and emotional wellbeing.', 'video', 'https://img.youtube.com/vi/BCGaSBf4Z_I/maxresdefault.jpg', 'https://www.youtube.com/watch?v=BCGaSBf4Z_I', 'horizontal', 266, now() - (7 * interval '1 second'), true, 'Social work is a bridge between care, family, and systems when people are making some of life''s hardest transitions.'),
    ('ltc-careers-008', 'music-therapy-career-long-term-care', 'Music Therapy: A Career in Long-Term Care', 'See how music therapy uses creativity, memory, emotion, and clinical goals to support residents in long-term care.', 'video', 'https://img.youtube.com/vi/cDCnuvAzBho/hqdefault.jpg', 'https://www.youtube.com/watch?v=cDCnuvAzBho', 'horizontal', 130, now() - (8 * interval '1 second'), true, 'Music therapy turns artistic skill into health-care impact, especially for residents whose needs go beyond words.'),
    ('ltc-careers-009', 'personal-support-workers-making-difference-long-term-care', 'Personal Support Workers: Making a Difference in Long-Term Care', 'A close look at personal support workers and the hands-on help, observation, and trust they bring to long-term care every day.', 'video', 'https://img.youtube.com/vi/XgrzJnA5HSU/maxresdefault.jpg', 'https://www.youtube.com/watch?v=XgrzJnA5HSU', 'horizontal', 174, now() - (9 * interval '1 second'), true, 'Personal support workers often know residents best because their work is built from repeated moments of practical care.'),
    ('ltc-careers-010', 'edge-factor-career-profiles-food-service-worker', 'Edge Factor Career Profiles: Food Service Worker', 'An Edge Factor profile of a food service worker, showing the pace, teamwork, and service mindset behind long-term care meals.', 'video', 'https://img.youtube.com/vi/G4XmgoamJUc/maxresdefault.jpg', 'https://www.youtube.com/watch?v=G4XmgoamJUc', 'horizontal', 167, now() - (10 * interval '1 second'), true, 'Food service can be an entry point into health care for students who like hands-on work and serving people directly.'),
    ('ltc-careers-011', 'edge-factor-career-profiles-personal-support-worker', 'Edge Factor Career Profiles: Personal Support Worker', 'An Edge Factor profile of a personal support worker and the daily care, communication, and responsibility the role involves.', 'video', 'https://img.youtube.com/vi/cweuFkXTSZU/hqdefault.jpg', 'https://www.youtube.com/watch?v=cweuFkXTSZU', 'horizontal', 204, now() - (11 * interval '1 second'), true, 'PSW work is personal, physical, and relational; it is a strong fit for people who want visible impact every shift.'),
    ('ltc-careers-012', 'edge-factor-career-profiles-rpn-ipac-lead', 'Edge Factor Career Profiles: Registered Practical Nurse - IPAC Lead', 'A career profile of a registered practical nurse working as an infection prevention and control lead in long-term care.', 'video', 'https://img.youtube.com/vi/oi5796gNgYE/hqdefault.jpg', 'https://www.youtube.com/watch?v=oi5796gNgYE', 'horizontal', 191, now() - (12 * interval '1 second'), true, 'Health-care roles can grow into specialties, leadership, and systems work without losing their connection to residents.'),
    ('ltc-careers-013', 'edge-factor-skilled-responders-long-term-care-administrator', 'Edge Factor Skilled Responders: Long-Term Care Administrator', 'A profile of long-term care administration and the coordination, leadership, and decision-making needed to keep a home running.', 'video', 'https://img.youtube.com/vi/6tvsbdvMMks/hqdefault.jpg', 'https://www.youtube.com/watch?v=6tvsbdvMMks', 'horizontal', 167, now() - (13 * interval '1 second'), true, 'Care homes also need operators and leaders who can balance people, policy, staffing, safety, and service.'),
    ('ltc-careers-014', 'neuro-behavioural-nurse-practitioner-career-long-term-care', 'Neuro-Behavioural Nurse Practitioner: A Career in Long-Term Care', 'See how a neuro-behavioural nurse practitioner supports complex resident needs through assessment, care planning, and collaboration.', 'video', 'https://img.youtube.com/vi/D8W2nJ1hj6w/hqdefault.jpg', 'https://www.youtube.com/watch?v=D8W2nJ1hj6w', 'horizontal', 253, now() - (14 * interval '1 second'), true, 'Specialized nursing careers can combine advanced clinical thinking with deep knowledge of how behaviour and environment interact.'),
    ('ltc-careers-015', 'nurse-practitioner-career-long-term-care', 'Nurse Practitioner: A Career in Long-Term Care', 'A look at the nurse practitioner role in long-term care, including advanced assessment, treatment decisions, and team-based support.', 'video', 'https://img.youtube.com/vi/A-O8IUMkmls/maxresdefault.jpg', 'https://www.youtube.com/watch?v=A-O8IUMkmls', 'horizontal', 297, now() - (15 * interval '1 second'), true, 'Nurse practitioners show how a nursing path can expand into diagnosis, prescribing, leadership, and complex care.'),
    ('ltc-careers-016', 'collaboration-long-term-care-soft-skills-on-the-job', 'Collaboration in Long-Term Care: Soft Skills on the Job', 'A soft-skills look at collaboration in long-term care and how different roles coordinate around resident needs.', 'video', 'https://img.youtube.com/vi/DMsgFb3E5co/hqdefault.jpg', 'https://www.youtube.com/watch?v=DMsgFb3E5co', 'horizontal', 173, now() - (16 * interval '1 second'), true, 'In care work, collaboration is not a bonus skill; it is how residents experience one connected team instead of separate jobs.'),
    ('ltc-careers-017', 'critical-thinking-long-term-care-soft-skills-on-the-job', 'Critical Thinking in Long-Term Care: Soft Skills on the Job', 'A soft-skills look at critical thinking in long-term care and how workers notice changes, weigh options, and make good calls.', 'video', 'https://img.youtube.com/vi/9T_BJ1bi8aQ/hqdefault.jpg', 'https://www.youtube.com/watch?v=9T_BJ1bi8aQ', 'horizontal', 163, now() - (17 * interval '1 second'), true, 'Critical thinking matters in hands-on care because small observations can change what a resident needs next.')
  on conflict (id) do update
    set slug = excluded.slug,
        title = excluded.title,
        description = excluded.description,
        content_type = excluded.content_type,
        thumbnail_url = excluded.thumbnail_url,
        video_url = excluded.video_url,
        video_orientation = excluded.video_orientation,
        video_duration = excluded.video_duration,
        published_at = excluded.published_at,
        is_published = excluded.is_published,
        takeaway = excluded.takeaway,
        updated_at = now();

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % long-term care rows upserted, got %', expected_count, actual_count;
  end if;

  insert into public.content_categories (content_id, category_id)
  select links.content_id, categories.id
  from (
    values
    ('ltc-careers-001', 'on-the-job'),
    ('ltc-careers-002', 'on-the-job'),
    ('ltc-careers-003', 'on-the-job'),
    ('ltc-careers-004', 'on-the-job'),
    ('ltc-careers-005', 'on-the-job'),
    ('ltc-careers-006', 'on-the-job'),
    ('ltc-careers-007', 'on-the-job'),
    ('ltc-careers-008', 'on-the-job'),
    ('ltc-careers-009', 'on-the-job'),
    ('ltc-careers-010', 'on-the-job'),
    ('ltc-careers-011', 'on-the-job'),
    ('ltc-careers-012', 'on-the-job'),
    ('ltc-careers-013', 'on-the-job'),
    ('ltc-careers-014', 'on-the-job'),
    ('ltc-careers-015', 'on-the-job'),
    ('ltc-careers-016', 'on-the-job'),
    ('ltc-careers-017', 'on-the-job')
  ) as links(content_id, category_slug)
  join public.categories categories on categories.slug = links.category_slug
  on conflict (content_id, category_id) do nothing;

  select count(*)
    into linked_count
  from public.content_categories cc
  join public.categories c on c.id = cc.category_id
  where cc.content_id in ('ltc-careers-001', 'ltc-careers-002', 'ltc-careers-003', 'ltc-careers-004', 'ltc-careers-005', 'ltc-careers-006', 'ltc-careers-007', 'ltc-careers-008', 'ltc-careers-009', 'ltc-careers-010', 'ltc-careers-011', 'ltc-careers-012', 'ltc-careers-013', 'ltc-careers-014', 'ltc-careers-015', 'ltc-careers-016', 'ltc-careers-017')
    and c.slug = 'on-the-job';

  if linked_count <> expected_count then
    raise exception 'Expected % long-term care category links, got %', expected_count, linked_count;
  end if;
end $$;
