-- Backfill reflection for the 7 'articles' rows.
-- Generated by scripts/generate-reflections-migration.py from scripts/data/reflections/articles.json.
-- Targets rows by stable id. Fails the transaction if the expected row
-- count is not updated.

do $$
declare
  expected_count int := 7;
  actual_count int;
begin
  with v(id, new_reflection) as (values
      ('12ea285e-557e-4f12-856b-2db012af7721', 'Resumes describe who you have been; what you create online describes who you are becoming. As you think about your next step after high school, what would you want a future employer to find when they search your name?'),
      ('1cf7ce0f-fe0a-4336-a923-770928620196', 'Interview prep is mostly about lowering the temperature when nerves run high. As you imagine your own first interview after high school, what would help you feel most yourself in the room: a list, a ritual, a person nearby, or something else?'),
      ('1ec760f3-60e8-4940-ab8b-6f534d1db91c', 'We tend to picture careers as the obvious ones we hear about at school. As you think about your own future work, what kind of place do you imagine actually walking into every day, and what would make it feel like the right one?'),
      ('5b776a32-411a-439c-b834-2761902d40ab', 'Job postings can sound far away from where you are right now. As you read this one, what part of the work feels like something you could grow into over time, and what part feels like a completely different planet?'),
      ('ac04d4a2-80d9-480d-a823-5722e3634b72', 'Some industries hide in plain sight until you notice how much depends on them. As you think about your own career options, would you rather work in something visible to the world, or in something the world only notices when it stops working?'),
      ('cf5cbfe4-30fa-4c27-aa9b-d9f5a2b33405', 'Some jobs ask you to figure out where money does the most good. As you think about your own values, would you rather build something new, fix something broken, or move resources to where they are needed most?'),
      ('fd0980f6-911b-4a3e-9ae7-b1d5a71b0cf3', 'Some jobs sit on the edge of new technology and old risks. As you think about your own future, do you want a career that watches the world change from the outside, or one that helps decide which changes are safe to make?')
  )
  update public.content c
  set reflection = v.new_reflection
  from v
  where c.id = v.id;

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
