-- Backfill reflection for the 8 'skills-canada-mindsets' rows.
-- Generated by scripts/generate-reflections-migration.py from scripts/data/reflections/skills-canada-mindsets.json.
-- Targets rows by stable id. Fails the transaction if the expected row
-- count is not updated.

do $$
declare
  expected_count int := 8;
  actual_count int;
begin
  with v(id, new_reflection) as (values
      ('skills-canada-035', 'Starting pay tells you almost nothing about what a career actually pays over time. As you think about your own options, what would change if you compared two paths by where they go in five years, instead of by where they start?'),
      ('skills-canada-067', 'Most business advice ages quickly because it focuses on tactics. As you think about what kind of work might endure, what is one need in your own life or community that you think will still be true in ten years?'),
      ('skills-canada-078', 'Most students prepare for a presentation by trying not to mess up. As you think about your next time in front of a group, what would change if you focused on landing one specific idea instead of getting through every slide?'),
      ('skills-canada-079', 'Some careers reward people who get curious about how things break. As you think about your own way of approaching problems, do you like tracing a broken system to its root, or would you rather build something new from scratch?'),
      ('skills-canada-096', 'Reputations about who belongs in a career take longer to update than the careers themselves. As you think about a path you might be talked out of, who would you want to talk to inside that field before you let the assumption stick?'),
      ('skills-canada-099', 'More young people are choosing trades after watching what debt does to friends in other paths. As you think about your own next step, what would it mean to optimize for being debt-free and certified, instead of for the most familiar option?'),
      ('skills-canada-100', 'Great work in many fields blurs the line between skills you can list and skills you have to feel. As you think about something you want to be good at, which kind of skill would you rather grow first, and how would you practice it?'),
      ('skills-canada-109', 'Some careers are not picked from a list; they are picked because something about the work felt obvious the first time you saw it. As you think back over the last year, has any kind of work surprised you by being more interesting than you expected?')
  )
  update public.content c
  set reflection = v.new_reflection
  from v
  where c.id = v.id;

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
