-- Refresh takeaway for the 8 life-skills Skills Canada videos (pilot batch).
-- Generated by scripts/generate-skills-canada-copy-migration.py from scripts/data/copy-updates/skills-canada-video-copy-update.json.
-- Targets rows by stable id; descriptions are intentionally left untouched.
-- Fails the transaction if the expected number of rows is not updated.

do $$
declare
  expected_count int := 8;
  actual_count int;
begin
  with v(id, new_takeaway) as (values
      ('skills-canada-040', 'Apprenticeship lets you learn a trade while you earn — high-school programs like OYAP turn that into a head start instead of a detour.'),
      ('skills-canada-058', 'Niche trades like sprinkler fitting are some of the steadiest paid work going — the trick is knowing they exist before you''re choosing a path.'),
      ('skills-canada-101', 'Trades aren''t a fallback — they''re one of the few careers where you can be earning, certified, and debt-free by 22.'),
      ('skills-canada-118', 'What makes a speaker engaging isn''t volume or charisma — it''s varying pace, energy, and emphasis so your voice carries the meaning.'),
      ('skills-canada-119', 'Introverts don''t need to become extroverts to speak well — preparation and a small ritual before you start do more than personality ever will.'),
      ('skills-canada-120', 'Stage fright shrinks with reps in low-stakes settings, not by hoping it''ll fade on its own.'),
      ('skills-canada-159', 'Filler words aren''t a habit — they''re what your mouth does when your brain hasn''t caught up; deliberate pauses sound far more confident.'),
      ('skills-canada-160', 'Mastery in public speaking comes from reps in front of real people — every talk you give is what makes the next one easier.')
  )
  update public.content c
  set takeaway = v.new_takeaway
  from v
  where c.id = v.id
    and c.content_type = 'video'
    and c.id like 'skills-canada-%';

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
