-- Refresh takeaway for the 4 problems-to-solve Skills Canada videos.
-- Generated by scripts/generate-skills-canada-copy.py from scripts/data/copy-updates/skills-canada-problems-to-solve-copy-update.json.
-- Targets rows by stable id; descriptions are intentionally left untouched.
-- Fails the transaction if the expected number of rows is not updated.

do $$
declare
  expected_count int := 4;
  actual_count int;
begin
  with v(id, new_takeaway) as (values
      ('skills-canada-031', 'Cloud platforms are how modern companies skip owning physical servers — the engineers behind them solve scale and reliability at a level no single business could match.'),
      ('skills-canada-092', 'Pastry''s hard problem isn''t creativity, it''s repeatability — the people who thrive treat precision and measurement as the actual craft.'),
      ('skills-canada-136', 'Standing out in a stack of resumes is a real problem — but the tactics that get you through usually aren''t the ones that hold up once you''re inside the company.'),
      ('skills-canada-154', 'Industrial process problems like better paint application don''t make headlines, but the engineers solving them cut cost, waste, and emissions at scales individual decisions can''t touch.')
  )
  update public.content c
  set takeaway = v.new_takeaway
  from v
  where c.id = v.id
    and c.content_type = 'video'
    and c.id like 'skills-canada-%';

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
