-- Seed "Print Nerd" YouTube shorts (Canadian Print Scholarships).
-- Source: https://www.youtube.com/@CanadianPrintScholarships/shorts
-- Generated by scripts/generate-print-nerd-migration.py from scripts/data/print-nerd-videos.json.

do $$
declare
  expected_count int := 6;
  expected_links int := 12;
  actual_count int;
  linked_count int;
  missing_categories text[];
begin
  select array_agg(expected.slug order by expected.slug)
    into missing_categories
  from (
    values
      ('emerging-careers'),
      ('on-the-job'),
      ('problems-to-solve')
  ) as expected(slug)
  left join public.categories categories on categories.slug = expected.slug
  where categories.id is null;

  if missing_categories is not null then
    raise exception 'Missing required categories: %', array_to_string(missing_categories, ', ');
  end if;

  insert into public.content (
    id,
    slug,
    title,
    description,
    content_type,
    thumbnail_url,
    video_url,
    video_orientation,
    video_duration,
    published_at,
    is_published,
    why_it_matters,
    planning_connection,
    takeaway,
    reflection
  )
  values
    ('print-nerd-001', 'swatch-books-choosing-paper', 'Swatch Books: How Printers Pick the Right Paper', 'Sheila visits the resource centre at Spicer Canada, where Matthew shows how swatch books let designers and printers feel paper textures and weights before committing to a job.', 'video', 'https://img.youtube.com/vi/gSRTIpqDKow/maxresdefault.jpg', 'https://www.youtube.com/watch?v=gSRTIpqDKow', 'vertical', 61, now() - (1 * interval '1 second'), true, 'Paper choice changes how a finished print looks and feels, so print suppliers keep whole libraries of samples. It is a reminder that creative industries run on specialist roles most students never hear about.', 'Roles like paper rep, print supplier, and production designer sit between art and manufacturing. Seeing how they work shows you where a love of design can meet a stable, hands-on career path.', 'In print, paper is not just what you print on. It is part of the whole design experience, and choosing it well is a skilled job.', 'A lot of creative work depends on people who pair an eye for design with technical know-how. As you explore options after high school, which hands-on craft or trade would you actually enjoy getting good at, and what is one way to try it?'),
    ('print-nerd-002', 'packaging-shelf-appeal', 'Packaging: Why Some Boxes Grab Your Eye First', 'Sheila breaks down how colour, texture, shape, and special print finishes are engineered into packaging so a product stands out on a crowded shelf before you ever see what is inside.', 'video', 'https://img.youtube.com/vi/h0KYnLtzM40/maxresdefault.jpg', 'https://www.youtube.com/watch?v=h0KYnLtzM40', 'vertical', 58, now() - (2 * interval '1 second'), true, 'Packaging design blends art, psychology, and print technology to win attention in a split second. It is a fast-moving field where creative and technical skills both pay off.', 'If you like the idea of work that mixes design with marketing and manufacturing, packaging is a real career lane. Noticing why a box works is the first step toward learning to make one.', 'Packaging is built to be noticed. Colour, texture, and finish do real work, and someone with design and print skills made every choice on purpose.', 'Every product on a shelf is competing for one second of your attention. As you think about life after high school, would you rather be the person solving that kind of creative problem, or the one building the technology behind it?'),
    ('print-nerd-003', 'photo-book-production', 'Photo Books: From Your Screen to 1,000 Books an Hour', 'Sheila follows a photo book from an online order to the production floor, where high-speed printers, robotic stackers, and binding machines turn digital pages into a finished, boxed book.', 'video', 'https://img.youtube.com/vi/INpr9rgVttM/maxresdefault.jpg', 'https://www.youtube.com/watch?v=INpr9rgVttM', 'vertical', 73, now() - (3 * interval '1 second'), true, 'The photo book you design online is finished by industrial printing, automation, and skilled operators. Modern print is a high-tech manufacturing world, not a dusty old trade.', 'Press operators, bindery technicians, and automation specialists keep these lines running. If you like machines, robotics, or precise hands-on work, print manufacturing is a path worth a look.', 'One case-bound book by hand takes about an hour. The same hour on an automated line can produce a thousand, and people run every step of that machinery.', 'Automation handles the repetitive work while people set up, monitor, and fix the machines. As you weigh your next step, does running and improving high-tech equipment sound like a path you would want to explore?'),
    ('print-nerd-004', 'stickers-and-large-format-signs', 'Stickers to Billboards: One Workflow, Every Size', 'Sheila walks the same design, print, laminate, and finish workflow that produces everything from small stickers to large-format signage, with quality checks before anything leaves the shop.', 'video', 'https://img.youtube.com/vi/PY0fUa_mDdw/maxresdefault.jpg', 'https://www.youtube.com/watch?v=PY0fUa_mDdw', 'vertical', 57, now() - (4 * interval '1 second'), true, 'Large-format print runs on shared steps and serious quality control, whatever the size. It shows how a single skill set scales from a sticker to a storefront sign.', 'Wide-format operators, finishers, and quality checkers are in demand as signage and branding grow. It is hands-on work with a clear, visible result you can point to.', 'A sticker and a giant sign follow the same path: design, print, laminate, finish, and inspect. The size changes, but the craft and the checks do not.', 'Some people love work where you can see a finished result at the end of the day. As you picture your next step, would a hands-on trade with a visible product suit you better than a screen-only job?'),
    ('print-nerd-005', 'manga-book-printing', 'How Manga Books Are Made: Plates to Spray Edges', 'Sheila goes inside a book printing company to follow a manga volume through pre-press, plate-making, papermaking, offset printing, folding, binding, and finishing touches like sprayed edges.', 'video', 'https://img.youtube.com/vi/hESI_YcUaiY/maxresdefault.jpg', 'https://www.youtube.com/watch?v=hESI_YcUaiY', 'vertical', 71, now() - (5 * interval '1 second'), true, 'Even a printed manga depends on pre-press, plate-making, papermaking, and offset presses working in sequence. The media you love is built by a chain of specialist roles.', 'Pre-press technician, press operator, and bindery worker are real jobs behind every book. If a favourite hobby like manga sparks you, print is one path that turns it into a career.', 'A manga volume passes through pre-press, plates, paper, press, and bindery before it reaches you. Each stage is a different skill and a different possible job.', 'Things you enjoy as a fan are made by people with specific, learnable skills. As you explore options after high school, is there a hobby you would want to follow into the industry that produces it?'),
    ('print-nerd-006', 'in-store-display-graphics', 'In-Store Display Graphics: How Store Signage Is Made', 'Sheila traces in-store marketing from design file to finished display, through large-format printing on vinyl, foam, and plastic, then trimming, packing, shipping, and installation in the aisle.', 'video', 'https://img.youtube.com/vi/Nm9Ii23HkJE/maxresdefault.jpg', 'https://www.youtube.com/watch?v=Nm9Ii23HkJE', 'vertical', 75, now() - (6 * interval '1 second'), true, 'The signs and displays guiding you through every store are produced, finished, and installed by a print team. Retail you see every day is quietly powered by this work.', 'Large-format printing, finishing, logistics, and install are all jobs in this pipeline. If you want variety across design, machines, and on-site work, in-store marketing offers several entry points.', 'Every display in a store is designed, printed, finished, shipped, and installed. One product moves through several different roles before it reaches the aisle.', 'A single store display passes through design, print, finishing, and install, each a different kind of job. As you think about your path, which of those stages would you most want to try first?')
  on conflict (id) do update
    set slug = excluded.slug,
        title = excluded.title,
        description = excluded.description,
        content_type = excluded.content_type,
        thumbnail_url = excluded.thumbnail_url,
        video_url = excluded.video_url,
        video_orientation = excluded.video_orientation,
        video_duration = excluded.video_duration,
        published_at = excluded.published_at,
        is_published = excluded.is_published,
        why_it_matters = excluded.why_it_matters,
        planning_connection = excluded.planning_connection,
        takeaway = excluded.takeaway,
        reflection = excluded.reflection,
        updated_at = now();

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % print-nerd rows upserted, got %', expected_count, actual_count;
  end if;

  insert into public.content_categories (content_id, category_id)
  select links.content_id, categories.id
  from (
    values
    ('print-nerd-001', 'emerging-careers'),
    ('print-nerd-001', 'on-the-job'),
    ('print-nerd-002', 'emerging-careers'),
    ('print-nerd-002', 'problems-to-solve'),
    ('print-nerd-003', 'emerging-careers'),
    ('print-nerd-003', 'on-the-job'),
    ('print-nerd-004', 'emerging-careers'),
    ('print-nerd-004', 'on-the-job'),
    ('print-nerd-005', 'emerging-careers'),
    ('print-nerd-005', 'on-the-job'),
    ('print-nerd-006', 'emerging-careers'),
    ('print-nerd-006', 'on-the-job')
  ) as links(content_id, category_slug)
  join public.categories categories on categories.slug = links.category_slug
  on conflict (content_id, category_id) do nothing;

  select count(*)
    into linked_count
  from public.content_categories cc
  where cc.content_id in ('print-nerd-001', 'print-nerd-002', 'print-nerd-003', 'print-nerd-004', 'print-nerd-005', 'print-nerd-006');

  if linked_count <> expected_links then
    raise exception 'Expected % print-nerd category links, got %', expected_links, linked_count;
  end if;
end $$;
