-- Refresh takeaway for the 25 how-i-got-here Skills Canada videos.
-- Generated by scripts/generate-skills-canada-copy.py from scripts/data/copy-updates/skills-canada-how-i-got-here-copy-update.json.
-- Targets rows by stable id; descriptions are intentionally left untouched.
-- Fails the transaction if the expected number of rows is not updated.

do $$
declare
  expected_count int := 25;
  actual_count int;
begin
  with v(id, new_takeaway) as (values
      ('skills-canada-001', 'Carpenter pay in cities like Vancouver scales sharply with years on tools. The number you find online is usually a midpoint, not what a first-year apprentice or a seasoned journeyman actually takes home.'),
      ('skills-canada-013', 'Real backyard projects teach what classes can''t: how to estimate, sequence, and fix mistakes you made yourself. A finished shed teaches more than a finished test.'),
      ('skills-canada-014', 'Art direction in games is rarely a job people aim at directly. Most people who hold it spent a decade as illustrators, animators, or designers first, picking up the breadth the role actually needs.'),
      ('skills-canada-016', 'First indie games are almost always smaller than the developer''s first idea. Shipping at all teaches more than aiming high and never releasing.'),
      ('skills-canada-020', 'Pastry shifts start before sunrise and end with everything you made gone by lunch. The career suits people who get satisfaction from the work itself, not from a finished product that sticks around.'),
      ('skills-canada-023', 'Photography businesses live or die on the parts most photographers ignore: pricing, contracts, and consistent client follow-up. The shooting is the easiest part of the job.'),
      ('skills-canada-025', 'Photography pay is bimodal: most photographers earn modestly while a small group commands premium rates. The split comes down to specialization and niche reputation, not raw talent.'),
      ('skills-canada-027', 'Video production companies that last are almost always built around a clear point of view, not gear lists. Clients can find a cheaper camera; they buy your judgment.'),
      ('skills-canada-036', 'Culinary school speeds the start of a chef''s career, but most working chefs got there through apprenticeship and years in restaurant kitchens. The credential is optional in a way it isn''t for most professions.'),
      ('skills-canada-042', 'Cabinetmakers who hit six figures usually own their work. The path runs through technical mastery, then a slow shift into estimating, client relationships, and running a small shop.'),
      ('skills-canada-055', 'Instrumentation and control techs sit at the intersection of mechanical and electrical work, with a layer of software on top. People who end up here often started in one of those fields and broadened into the others.'),
      ('skills-canada-061', 'Refrigeration mechanic work is steady in any climate that needs cooling, which is most of them. The path is a four-year apprenticeship and a Red Seal that travels across provinces.'),
      ('skills-canada-062', 'Refrigeration and AC mechanics show up when nothing else is working in extreme heat or cold. People drawn to the work tend to like the visibility of being the one who fixes it.'),
      ('skills-canada-072', 'Carpenter pay in cities like Vancouver scales sharply with years on tools. The number you find online is usually a midpoint, not what a first-year apprentice or a seasoned journeyman actually takes home.'),
      ('skills-canada-076', 'High-revenue days in a woodworking business come from custom commercial work, not retail furniture. The path there runs through niche reputation, not better marketing.'),
      ('skills-canada-091', 'Most serial entrepreneurs started with a small, unglamorous first business. The repeatable skill is starting at all, not picking a winner the first time.'),
      ('skills-canada-097', 'Career direction usually comes from trying enough small things to find what holds your attention. Waiting to commit until you''re "sure" is the slow path; trying things is the fast one.'),
      ('skills-canada-098', 'Career advice that worked for one person rarely transfers cleanly to another. The useful pattern in someone else''s path is the way they made decisions — not the decisions themselves.'),
      ('skills-canada-105', 'Career pivots in your 20s and 30s are more common than they look. Most people end up doing work that wasn''t on their radar at 18, and that''s usually a good outcome, not a failure of planning.'),
      ('skills-canada-106', 'Auto body apprenticeship programs through high school let you start earning before graduation. The OYAP path turns a couple of years of part-time school work into a head start on the trade.'),
      ('skills-canada-116', 'CNC machining sits halfway between trades and tech. The people who thrive usually had hands-on mechanical experience first, then learned the programming side on the job.'),
      ('skills-canada-121', 'Home labs are the fastest way into IT roles because they give you something concrete to talk about in interviews. Self-taught with proof beats certified with nothing built, in most hiring conversations.'),
      ('skills-canada-122', 'Systems administrator pay ranges widely depending on the kind of infrastructure you run. The bands jump sharply when you specialize: cloud, security, or large-scale networks.'),
      ('skills-canada-142', 'Breaking into animation is mostly about portfolio plus persistence. Studios hire from a small pool of people who keep showing them new work — not from cold applications alone.'),
      ('skills-canada-149', 'Software development is one of the few professional careers people switch into in months instead of years. The catch: the first job is the hardest, and self-taught candidates have to make their work visible to get a chance.')
  )
  update public.content c
  set takeaway = v.new_takeaway
  from v
  where c.id = v.id
    and c.content_type = 'video'
    and c.id like 'skills-canada-%';

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
