-- Backfill reflection for the 27 'skills-canada-emerging-careers' rows.
-- Generated by scripts/generate-reflections-migration.py from scripts/data/reflections/skills-canada-emerging-careers.json.
-- Targets rows by stable id. Fails the transaction if the expected row
-- count is not updated.

do $$
declare
  expected_count int := 27;
  actual_count int;
begin
  with v(id, new_reflection) as (values
      ('skills-canada-002', 'Apprenticeship works because of who is one or two stages ahead of you, not just what you are studying. As you think about how you learn, would you rather pick a path because of the curriculum, or because of the people you would be learning beside?'),
      ('skills-canada-006', 'Some careers let you start earning while you are still in school. As you think about your own next few years, would it feel different to be paid to learn a trade, instead of paying to learn one?'),
      ('skills-canada-007', 'The rules around how careers start can change in your favour without you noticing. As you think about a path you have considered, when was the last time you checked whether the requirements or supports have changed since you first looked?'),
      ('skills-canada-008', 'Some credentials work everywhere in Canada; others lock you into one province. As you think about your own future, how much would it matter to you to have a qualification that lets you move without starting over?'),
      ('skills-canada-009', 'Some careers let you see the work before committing in a way most do not. As you think about a path you are curious about, where could you go for a few hours to find out what the day actually looks like?'),
      ('skills-canada-028', 'Some jobs sit at the cleanest intersection of tech and trades. As you think about your own preferences, do you like the satisfaction of producing a physical thing, the satisfaction of writing the program that produces it, or both at once?'),
      ('skills-canada-033', 'Software careers branch sideways more than they climb. As you imagine your own future in tech, would you specialize in something other engineers depend on, or stay closer to the parts users see and use every day?'),
      ('skills-canada-039', 'Some careers sit in a middle ground between two industries and benefit from staying there. As you think about your own interests, where would you want to live: deep inside one field, or on the seam between two?'),
      ('skills-canada-041', 'Many trades careers split between generalists who do okay and specialists who do much better. As you think about your own appetite for risk, would you rather have many options at average pay, or fewer options at higher pay?'),
      ('skills-canada-046', 'Some trades span industries that pay very differently for the same skills. As you think about a craft you might learn, would you rather master the technique and figure out the highest-paying industry later, or pick the industry first?'),
      ('skills-canada-050', 'Some certifications are harder to get because the systems they work on are higher stakes. As you think about your own appetite for difficulty, are you drawn to fields where the barrier to entry quietly filters out the competition?'),
      ('skills-canada-056', 'Some work outlasts the worker. As you think about what you want your career to leave behind, would it matter to you that someone walks past something you built and feels it was solid a hundred years from now?'),
      ('skills-canada-065', 'Small businesses succeed by serving one kind of client well, not by trying to serve everyone. As you think about something you might one day sell, who would you most want to work with regularly, and what would they keep coming back for?'),
      ('skills-canada-066', 'In many creative fields, the highest pay goes to people who can do more than just the core craft. As you think about a creative job you might want, what adjacent skill would let you stand out from people who only do the visual side?'),
      ('skills-canada-069', 'Some specialized skills stay valuable because automation has not caught up. As you think about a career, would you rather pick something hard to automate, or something efficient enough that automation is unlikely to come for it?'),
      ('skills-canada-073', 'Some businesses scale by repeating simple work for the same clients, not by inventing new services. As you think about something you might one day run, would you find it satisfying to do the same thing well, again and again, for years?'),
      ('skills-canada-081', 'Designers who think only about the work itself usually struggle. As you think about a creative field you are drawn to, what would it mean to learn the business side as seriously as the craft side, instead of after the fact?'),
      ('skills-canada-082', 'Pay does not always map to credentials. As you think about your own career options, what would change if you measured them by what they actually pay top performers, instead of by how prestigious the title sounds?'),
      ('skills-canada-083', 'The highest-paying trades usually come with trade-offs in location, hazard, or hours. As you think about your own preferences, what would you give up willingly for top pay, and what would feel like too high a price?'),
      ('skills-canada-084', 'Hourly wage is only one number in the picture. As you compare jobs, what would change if you looked at total compensation across a year, including overtime, benefits, and the seasons you would actually work?'),
      ('skills-canada-087', 'Many trades careers have a stage past the obvious ones, where you start running the work instead of doing it. As you imagine yourself ten years in, would you want to still be on the tools, managing other people, or running the whole shop?'),
      ('skills-canada-088', 'Most trades have an entry-level version and a high-end specialization with much better pay. As you think about your own next step, what would it take to plan early for the specialization, instead of arriving at it accidentally?'),
      ('skills-canada-089', 'A career that looks short on paper can still be long in practice. As you imagine your own working day, how much do hours of standing, irregular client flow, or talking to strangers matter to you when comparing jobs?'),
      ('skills-canada-107', 'Most jobs are not being replaced by AI; they are being reshaped by it. As you think about a career you might enter, what would it mean to learn the tools early enough that you become more valuable instead of less?'),
      ('skills-canada-113', 'Some technologies show up in more industries every year. As you think about the next decade of work, would you rather pick a skill that is widely useful across many fields, or one that goes deep in just one?'),
      ('skills-canada-114', 'Some careers are bets on where the world is going. As you think about your own future, would you pick a discipline because it is well established, or because you believe the next generation of products will need exactly what it teaches?'),
      ('skills-canada-117', 'Some skills transfer across industries that pay very differently. As you think about a craft you might learn, would you rather master something niche to one industry, or master something useful in aerospace, medical, and custom industrial work all at once?')
  )
  update public.content c
  set reflection = v.new_reflection
  from v
  where c.id = v.id;

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
