-- Refresh takeaway for the 61 on-the-job Skills Canada videos.
-- Generated by scripts/generate-skills-canada-copy.py from scripts/data/copy-updates/skills-canada-on-the-job-copy-update.json.
-- Targets rows by stable id; descriptions are intentionally left untouched.
-- Fails the transaction if the expected number of rows is not updated.

do $$
declare
  expected_count int := 61;
  actual_count int;
begin
  with v(id, new_takeaway) as (values
      ('skills-canada-004', 'TV set construction runs on impossible deadlines and constant rebuilds. The job suits people who measure satisfaction in finished episodes, not finished objects.'),
      ('skills-canada-005', 'The last 5% of a TV episode swallows half the schedule. Working in broadcast means accepting that the final hour will always be the most intense, and treating that as the job, not a problem.'),
      ('skills-canada-011', 'Six-figure landscaping projects come with logistics most clients never see: equipment scheduling, crew coordination, and pricing risk. The estimation work happens before the first shovel.'),
      ('skills-canada-012', 'Trades creators on social media are reshaping what students see about real work in their field. Watching how they document a day is itself a useful skill for evaluating careers from the outside.'),
      ('skills-canada-015', 'Software choice is often a creative decision dressed as a technical one. Picking tools that match how you actually work usually beats picking the industry-standard one.'),
      ('skills-canada-018', 'Creative careers in fashion are often a slow ladder of small public moments — markets, pop-ups, friends'' projects — that quietly compound into legitimate ones.'),
      ('skills-canada-019', 'Fashion design is more production scheduling and supplier management than sketching. Most working designers spend more time on logistics than aesthetics.'),
      ('skills-canada-021', 'Bakery jobs start before sunrise on day one. The career suits people who can shift their sleep schedule and find satisfaction in finishing a shift before most people start theirs.'),
      ('skills-canada-022', 'Baking is physical: lifting flour bags, standing through long shifts, moving hot trays. People who thrive treat the fitness side as part of the craft, not a side effect.'),
      ('skills-canada-024', 'Adventure photography is closer to fieldwork than studio work. The pay reflects what you''ll endure to get the shot, and the careers reward people who can keep their head in conditions that distract everyone else.'),
      ('skills-canada-026', 'Most days at a video production company aren''t shooting — they''re prep, edit, client calls, and email. The shoot days look glamorous because they''re rare.'),
      ('skills-canada-029', 'CNC machinist days alternate between setup, programming, and watching the machine run. The skill is staying alert during the long cycles so problems get caught before parts get scrapped.'),
      ('skills-canada-030', 'A CNC lathe at work shows the appeal of the trade: it''s precise enough to feel like math made physical. The careers reward people who like the feedback loop between a program and a part that comes out exactly right.'),
      ('skills-canada-032', 'Cloud engineers build the systems other software runs on. The job suits people who like infrastructure-level problems, where small decisions affect every team downstream.'),
      ('skills-canada-034', 'Three-star Michelin kitchens are unforgiving by design. The cooks who last treat the intensity as training, not punishment, and most leave with skills that hold up anywhere else.'),
      ('skills-canada-037', 'Esthetician days are heavy on close client contact and consistent technique. The work pays best when you can build a loyal clientele over years, which takes more interpersonal skill than the technical side.'),
      ('skills-canada-038', 'Each esthetics treatment is a small project: assess, prep, execute, follow up. The career compounds when you turn first-time clients into a regular book that''s stable across slow seasons.'),
      ('skills-canada-043', 'Plumbing apprenticeships are mostly fetch-and-hold-and-watch for the first year. The ones who progress fast pay attention even when they''re not the ones doing the work.'),
      ('skills-canada-044', 'Plumbing fundamentals like flow, pressure, venting, and code are universal across residential and commercial work. Mastering them early lets you specialize later without restarting.'),
      ('skills-canada-047', 'Sheet metal fabrication moves between layout, bending, and welding in a single shift. People drawn to the trade tend to like seeing a flat sheet become a three-dimensional object in a few hours.'),
      ('skills-canada-048', 'Pipe fitting work happens on big sites: industrial, marine, refinery. The trade pays for the willingness to travel and the precision to get long welds right under pressure.'),
      ('skills-canada-049', 'Working pipefitter days revolve around blueprint reading, layout, and welding. The career suits people who like working on a connected system rather than discrete pieces.'),
      ('skills-canada-052', 'Welding shifts in production environments are about throughput as much as quality. The welders who get promoted can do both: hold the quality bar while making the daily numbers.'),
      ('skills-canada-054', 'Architectural technologists spend most of their day in software, producing the drawings that builders will follow. The work suits detail-oriented people who like the certainty of constructable documents.'),
      ('skills-canada-057', 'Union bricklaying in big cities is structured around clear roles, schedules, and pay scales. The trade-off is a strict ladder that rewards patience over hustle.'),
      ('skills-canada-059', 'Sprinkler fitters install systems most people will never see in action. The career pays for the rare combination of physical work and life-safety responsibility.'),
      ('skills-canada-060', 'HVAC techs alternate between scheduled maintenance and emergency calls. The career rewards people who can stay calm when someone''s furnace dies at -20°C and they''re the only one who can fix it.'),
      ('skills-canada-063', 'Plumbing builds confidence as much as skill. The first few years are mostly about doing jobs you''ve watched done many times, and repetition turns nervous apprentices into competent journeymen.'),
      ('skills-canada-064', 'High-revenue painting careers come from custom work at the top of the market: bespoke car finishes, restoration, or murals. The path is reputation plus very specific technical mastery.'),
      ('skills-canada-068', 'Composition tricks like this one only land when you''ve already done the boring framing work hundreds of times. The visible technique sits on top of invisible reps.'),
      ('skills-canada-070', 'Three-star Michelin kitchens are unforgiving by design. The cooks who last treat the intensity as training, not punishment, and most leave with skills that hold up anywhere else.'),
      ('skills-canada-071', 'Electrician days mix predictable installation work and unpredictable troubleshooting. The career suits people who can switch between methodical and improvisational without losing focus.'),
      ('skills-canada-075', 'Heritage and restoration masonry uses bricks and techniques that haven''t changed in centuries. The apprentices doing this work end up with a portfolio that high-end clients pay a premium for.'),
      ('skills-canada-077', 'Bakery shifts are repetitive on purpose: the same mixes, the same shapes, the same hours. People who stay treat the repetition as a chance to refine, not a reason to leave.'),
      ('skills-canada-080', 'Custom paint at this level is closer to fine art than auto body. The price covers labour you don''t see: surface prep, masking, candy coats, and clear, each one taking days.'),
      ('skills-canada-085', 'Workplace safety is mostly about catching small issues before they become incidents. The skill is noticing what''s slightly off when everyone else is busy moving fast.'),
      ('skills-canada-086', 'Prep cooks set the rhythm of a restaurant before service begins. The work is unglamorous but visible to every chef in the kitchen, and good prep cooks get pulled into better stations quickly.'),
      ('skills-canada-090', 'Plumbing covers more ground than people expect: residential service, new construction, commercial, industrial, gas. Picking a niche early lets your skill compound in one direction.'),
      ('skills-canada-093', 'Canada has a structural shortage of trades workers, which is good news for anyone entering. The shortage isn''t going away in the next decade, and pay reflects it.'),
      ('skills-canada-102', 'Safety professionals spend most of their time on site walks, training, and documentation. The job suits people who can balance enforcement with relationship-building so workers actually follow the rules.'),
      ('skills-canada-103', 'Strong safety culture is less about rules and more about social norms — what coworkers expect of each other when no one''s watching. The skill in safety work is changing those norms, not just posting them.'),
      ('skills-canada-104', 'WHMIS isn''t a one-time training; the chemicals in any workplace change, and so do the symbols and rules. Treating it as a recurring habit, not a checkbox, is what makes it useful.'),
      ('skills-canada-108', 'Auto body work has shifted with aluminum panels, electric vehicles, and ADAS systems. Technicians who stay current keep their value; the ones who don''t get squeezed out by specialists.'),
      ('skills-canada-111', 'Millwright training at colleges like Loyalist is hands-on by design, and the work is on real industrial systems. Graduates often walk into apprenticeships at the companies they trained on.'),
      ('skills-canada-115', 'CNC machinist days alternate between setup, programming, and watching the machine run. The skill is staying alert during the long cycles so problems get caught before parts get scrapped.'),
      ('skills-canada-125', 'Aerospace engineers spend more time on simulation, review meetings, and paperwork than on physical prototypes. The work pays for the discipline to be slow when the stakes are high.'),
      ('skills-canada-128', 'Automotive techs now spend more time at a laptop than under a car. Diagnostics is the high-value skill, and the technicians who get there fastest invest in software training, not just tools.'),
      ('skills-canada-129', 'Outdoor power equipment technicians work on everything from chainsaws to snowmobiles. The career rewards people who like small engines and don''t mind the seasonal swings.'),
      ('skills-canada-131', 'OPET careers are quieter than auto mechanics, but the demand is steady because every cottage, farm, and worksite runs on this equipment. The training is shorter and the niche is well-defined.'),
      ('skills-canada-132', 'Competition baking shows what mastery looks like in the trade: speed, consistency, and presentation under judging conditions. Watching it is one of the best ways to calibrate your own standards.'),
      ('skills-canada-133', 'Plumbing fundamentals like flow, pressure, venting, and code are universal across residential and commercial work. Mastering them early lets you specialize later without restarting.'),
      ('skills-canada-134', 'Sewing as a trade looks simple at competition speed because the foundation work has been internalized. The same is true of every demonstrated skill — the visible part is the smallest fraction of the practice.'),
      ('skills-canada-138', 'Graphic designer days are roughly half production and half coordination. The career suits people who can move between detailed visual work and the conversations that decide what to make.'),
      ('skills-canada-140', 'Freelance design careers are more business than craft after the first year. The successful freelancers spend hours on pricing, contracts, and client management for every hour on layout.'),
      ('skills-canada-143', '3D animator days are long, iterative, and quiet. Most of the work is watching the same five seconds of motion until it looks right, then doing it again with notes.'),
      ('skills-canada-146', 'Electronic control technicians work on the systems that automate factories. The career sits between technician and engineer, and people who can read schematics and write basic code do best.'),
      ('skills-canada-148', 'Big-company software engineering involves a lot more meetings and code review than people expect. The actual coding fits between coordination, not the other way around.'),
      ('skills-canada-151', 'Manufacturing co-ops give engineering students the rare chance to see decisions play out on a production line. The students who get noticed treat it as a real job, not a school placement.'),
      ('skills-canada-153', 'Factory paint lines are a system: pre-treatment, primer, base, clear, robotic spray, oven cure. Knowing the steps helps when you decide whether you''d rather build the system or operate it.'),
      ('skills-canada-157', 'WorldSkills competitions show the upper limit of trade performance under judging conditions. Watching them is useful for understanding what mastery in your trade actually looks like.'),
      ('skills-canada-158', 'Apprentice electrician work is mostly assisting until you''ve passed enough check-ins to do tasks independently. The path forward is being useful in small ways consistently, not impressive occasionally.')
  )
  update public.content c
  set takeaway = v.new_takeaway
  from v
  where c.id = v.id
    and c.content_type = 'video'
    and c.id like 'skills-canada-%';

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
