-- Backfill reflection for the 14 'skills-canada-post-secondary' rows.
-- Generated by scripts/generate-reflections-migration.py from scripts/data/reflections/skills-canada-post-secondary.json.
-- Targets rows by stable id. Fails the transaction if the expected row
-- count is not updated.

do $$
declare
  expected_count int := 14;
  actual_count int;
begin
  with v(id, new_reflection) as (values
      ('skills-canada-003', 'Certificates open doors but rarely close paths. As you think about your own next step, would it feel right to start with a credential that gets you working quickly, knowing the deeper learning happens after you are already in the trade?'),
      ('skills-canada-010', 'Policy details around training can quietly remove or add big barriers. As you think about your own path, how much would it shift your options if money for training was easier to find, and would you actually check before deciding?'),
      ('skills-canada-017', 'Creative programs judge portfolios on point of view, not polish. As you think about something you might apply to, what would your work look like if you stopped trying to impress reviewers and showed them what you actually care about?'),
      ('skills-canada-045', 'Some programs hand you a finished credential; others hand you the start of one. As you think about your own next step, would you rather complete a path inside school, or finish it on real job sites with people already doing the work?'),
      ('skills-canada-051', 'Some careers let you start working and stack credentials as you go. As you think about your own pace, would it feel better to wait until you are fully qualified before earning, or to start small and grow your title over time?'),
      ('skills-canada-053', 'There is usually more than one way into an industry. As you think about a field you are drawn to, would you rather take the long, traditional route, or the faster one that puts you next to the work without the same title?'),
      ('skills-canada-074', 'Some kinds of training mostly happen by doing the work with real people. As you think about a craft you might learn, where would you want most of your hours spent: in lectures, in a practice studio, or in front of actual clients from day one?'),
      ('skills-canada-124', 'Some careers pay back over decades, not in the first job. As you think about your own patience, would you rather pick a path where the rewards come quickly, or one that asks for years of depth before the work starts feeling like enough?'),
      ('skills-canada-127', 'Programs that prepare you for the industry as it was can feel safe at the time and outdated five years later. As you compare schools, what would change if you picked the one whose curriculum looks ahead, instead of the one with the longest history?'),
      ('skills-canada-130', 'Some careers go where the workers are; others pull the workers wherever the work is. As you think about your own next step, would you mind moving to follow the job, or do you need a path that lets you stay rooted somewhere specific?'),
      ('skills-canada-137', 'Fulfilling careers usually live at the overlap of what you would do for free and what someone will pay for. As you think about what you already do without being asked, where might that overlap exist for you, even if it takes years to find?'),
      ('skills-canada-144', 'Some training programs build the muscle to diagnose problems; others just build vocabulary about them. As you think about a field you might enter, how would you tell which kind of program you were actually choosing before you committed?'),
      ('skills-canada-150', 'Some programs are closer to a profession than to a degree. As you imagine your own next four years, would it feel motivating to be trained like a future engineer from day one, or would you want more room to figure out what you want first?'),
      ('skills-canada-156', 'Career paths sometimes fork earlier than you expect. As you think about a craft you might learn, would you rather train for steady volume work inside someone else''s shop, or for one-off creative pieces in a shop you eventually run yourself?')
  )
  update public.content c
  set reflection = v.new_reflection
  from v
  where c.id = v.id;

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
