-- Backfill reflection for the 4 'skills-canada-problems-to-solve' rows.
-- Generated by scripts/generate-reflections-migration.py from scripts/data/reflections/skills-canada-problems-to-solve.json.
-- Targets rows by stable id. Fails the transaction if the expected row
-- count is not updated.

do $$
declare
  expected_count int := 4;
  actual_count int;
begin
  with v(id, new_reflection) as (values
      ('skills-canada-031', 'Most of the technology you use every day depends on systems you cannot see. As you think about what kind of work you might do, are you drawn to the visible side of products, or to the invisible infrastructure that lets everything else work?'),
      ('skills-canada-092', 'Some jobs reward creativity; others reward doing the same thing perfectly, again and again. As you think about your own strengths, which one feels more like you, and what would it mean to be paid for that exact ability?'),
      ('skills-canada-136', 'Almost every career path will tempt you to take a shortcut at some point. As you think about your own way of working, what kind of corner are you willing to cut, and where is the line you would not cross even for an offer?'),
      ('skills-canada-154', 'Some of the biggest changes in the world come from people improving things you would never notice. As you imagine your own working life, would you rather work on visible products, or on the invisible processes that make millions of products possible?')
  )
  update public.content c
  set reflection = v.new_reflection
  from v
  where c.id = v.id;

  get diagnostics actual_count = row_count;
  if actual_count <> expected_count then
    raise exception 'Expected % rows updated, got %', expected_count, actual_count;
  end if;
end $$;
